/**
 * Achievement (Thành Tựu) catalog foundation — Phase 11.10.A
 *
 * Pure data + deterministic helpers. KHÔNG runtime/schema/migration.
 *
 * Design intent (P11-10):
 * - Static catalog cho AchievementDef song song với MissionDef nhưng khác
 *   semantic: mission DAILY/WEEKLY/ONCE tracker reward; achievement là milestone
 *   one-time reward + cosmetic title unlock + permanent record.
 * - Reuse `MissionGoalKind` enum (`KILL_MONSTER`, `CLEAR_DUNGEON`, `BOSS_HIT`,
 *   `BREAKTHROUGH`, `GAIN_EXP`, `CULTIVATE_SECONDS`, `BUY_LISTING`,
 *   `SELL_LISTING`, `CHAT_MESSAGE`, `SECT_CONTRIBUTE`) để Phase 11.10.B service
 *   share tracking logic với mission service.
 * - Category variety: combat / cultivation / exploration / social / economy /
 *   milestone / collection.
 * - Tier (rarity-equivalent): bronze / silver / gold / platinum / diamond
 *   (matching achievement convention in MMO).
 * - rewardTitleKey link với `titles.ts` `titleForAchievement` lookup → khi
 *   achievement complete, auto-unlock title (Phase 11.10.B + 11.9.B service
 *   wire `unlockTitle`).
 *
 * Phase 11.10.B runtime sẽ thêm Prisma `CharacterAchievement { id, characterId,
 *   achievementKey, progress, completedAt? }` + service `incrementAchievement`
 *   (idempotent on `[characterId, achievementKey]`) + `claimAchievement`
 *   (validate `completedAt!=null` + grant reward + auto-unlock title qua
 *   `titleForAchievement(key)`) + event listener cho mỗi `goalKind`.
 *
 * Phase 11.10.F — `reward.items` non-empty exemplars: `first_breakthrough`
 *   (5× huyet_chi_dan) + `first_dungeon_clear` (3× tinh_thiet) thực thi wire
 *   `achievement.service.claimAchievement` → `InventoryService.grantTx` qua
 *   `ItemLedger reason='ACHIEVEMENT_REWARD'`. Các achievement còn lại vẫn
 *   giữ item-empty để economy nhẹ (bảo vệ inventory bloat early game).
 *
 * Curve (32 achievement baseline):
 * - Combat: 8 (first kill / 100 kill / 1000 kill / element-specialist × 5).
 * - Cultivation: 6 (first breakthrough / mỗi major realm milestone).
 * - Exploration: 5 (first dungeon / 10 dungeon / 100 dungeon / boss / element
 *   dungeon).
 * - Social: 4 (sect join / first chat / first contribute / sect elder).
 * - Economy: 4 (first buy / first sell / 1m linhthach earned / 10m).
 * - Milestone: 3 (first login / 30-day login / 365-day login).
 * - Collection: 2 (collect 50 item / collect 100 item).
 */

import type { ElementKey } from './combat';
import type { MissionGoalKind } from './missions';

export type AchievementTier =
  | 'bronze'
  | 'silver'
  | 'gold'
  | 'platinum'
  | 'diamond';

export type AchievementCategory =
  | 'combat'
  | 'cultivation'
  | 'exploration'
  | 'social'
  | 'economy'
  | 'milestone'
  | 'collection';

export interface AchievementReward {
  readonly linhThach?: number;
  readonly tienNgoc?: number;
  readonly exp?: number;
  readonly items?: ReadonlyArray<{ readonly itemKey: string; readonly qty: number }>;
}

export interface AchievementDef {
  readonly key: string;
  readonly nameVi: string;
  readonly nameEn: string;
  readonly description: string;
  readonly category: AchievementCategory;
  readonly tier: AchievementTier;
  /**
   * Tracking goalKind (reuse MissionGoalKind). Phase 11.10.B service wire
   * cùng event listener với mission service.
   */
  readonly goalKind: MissionGoalKind;
  /** Số lượng cần đạt để complete. */
  readonly goalAmount: number;
  /** Element affinity (null = neutral). */
  readonly element: ElementKey | null;
  /**
   * Title key sẽ unlock khi complete (link với `titles.ts`
   * `titleForAchievement` lookup).
   */
  readonly rewardTitleKey: string | null;
  readonly reward: AchievementReward;
  /**
   * Hidden achievement (chỉ hiện khi complete). Default false.
   */
  readonly hidden: boolean;
}

/**
 * 32 achievement baseline cover combat / cultivation / exploration / social
 * / economy / milestone / collection × bronze → diamond tier.
 *
 * Stable order: category → tier ascending → key alphabetical.
 */
export const ACHIEVEMENTS: readonly AchievementDef[] = [
  // ===== COMBAT — 8 =====
  {
    key: 'first_monster_kill',
    nameVi: 'Sơ Sát',
    nameEn: 'First Blood',
    description: 'Lần đầu chính thức ra tay sát địch.',
    category: 'combat',
    tier: 'bronze',
    goalKind: 'KILL_MONSTER',
    goalAmount: 1,
    element: null,
    rewardTitleKey: 'achievement_first_kill',
    reward: { linhThach: 100, exp: 50 },
    hidden: false,
  },
  {
    key: 'kill_100_monsters',
    nameVi: 'Bách Sát Tiên',
    nameEn: 'Hundred Slayer',
    description: 'Sát hạ 100 địch nhân.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_000, exp: 500 },
    hidden: false,
  },
  {
    key: 'kill_1000_monsters',
    nameVi: 'Thiên Sát Yêu Tu',
    nameEn: 'Thousand Slayer',
    description: 'Sát hạ 1000 địch nhân.',
    category: 'combat',
    tier: 'gold',
    goalKind: 'KILL_MONSTER',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 10_000, exp: 5_000 },
    hidden: false,
  },
  {
    key: 'first_boss_kill',
    nameVi: 'Đồ Lục Yêu Vương',
    nameEn: 'Boss Slayer',
    description: 'Đầu tiên đánh hạ một yêu vương.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'BOSS_HIT',
    goalAmount: 1,
    element: null,
    rewardTitleKey: 'achievement_first_boss',
    reward: { linhThach: 2_000, exp: 1_000 },
    hidden: false,
  },
  {
    key: 'kim_specialist',
    nameVi: 'Kim Hệ Chuyên Tinh',
    nameEn: 'Kim Element Specialist',
    description: 'Sát hạ 50 địch nhân hệ Kim.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 50,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 800, exp: 400 },
    hidden: false,
  },
  {
    key: 'moc_specialist',
    nameVi: 'Mộc Hệ Chuyên Tinh',
    nameEn: 'Moc Element Specialist',
    description: 'Sát hạ 50 địch nhân hệ Mộc.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 50,
    element: 'moc',
    rewardTitleKey: null,
    reward: { linhThach: 800, exp: 400 },
    hidden: false,
  },
  {
    key: 'thuy_specialist',
    nameVi: 'Thuỷ Hệ Chuyên Tinh',
    nameEn: 'Thuy Element Specialist',
    description: 'Sát hạ 50 địch nhân hệ Thuỷ.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 50,
    element: 'thuy',
    rewardTitleKey: null,
    reward: { linhThach: 800, exp: 400 },
    hidden: false,
  },
  {
    key: 'hoa_specialist',
    nameVi: 'Hoả Hệ Chuyên Tinh',
    nameEn: 'Hoa Element Specialist',
    description: 'Sát hạ 50 địch nhân hệ Hoả.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 50,
    element: 'hoa',
    rewardTitleKey: null,
    reward: { linhThach: 800, exp: 400 },
    hidden: false,
  },

  // ===== CULTIVATION — 6 =====
  {
    key: 'first_breakthrough',
    nameVi: 'Đột Phá Nhất Trọng',
    nameEn: 'First Breakthrough',
    description: 'Lần đầu vượt qua bình cảnh, lên trọng kế tiếp.',
    category: 'cultivation',
    tier: 'bronze',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 1,
    element: null,
    rewardTitleKey: 'achievement_first_breakthrough',
    // Phase 11.10.F — first non-empty `reward.items` to exercise wire of
    // PR #277 (`achievement.service.claimAchievement` → `inventory.grantTx`
    // qua `ItemLedger reason='ACHIEVEMENT_REWARD'`). 5× huyet_chi_dan = HP
    // pill PHAM giúp player sống sót fight đầu sau breakthrough.
    reward: {
      linhThach: 200,
      exp: 100,
      items: [{ itemKey: 'huyet_chi_dan', qty: 5 }],
    },
    hidden: false,
  },
  {
    key: 'reach_truc_co',
    nameVi: 'Trúc Cơ Đăng Đỉnh',
    nameEn: 'Foundation Established',
    description: 'Đạt cảnh giới Trúc Cơ.',
    category: 'cultivation',
    tier: 'silver',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 10,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_500, exp: 800 },
    hidden: false,
  },
  {
    key: 'reach_kim_dan',
    nameVi: 'Kim Đan Hữu Thành',
    nameEn: 'Golden Core Achieved',
    description: 'Đạt cảnh giới Kim Đan.',
    category: 'cultivation',
    tier: 'gold',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 19,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 5_000, exp: 3_000 },
    hidden: false,
  },
  {
    key: 'reach_nguyen_anh',
    nameVi: 'Nguyên Anh Xuất Khiếu',
    nameEn: 'Nascent Soul Emerges',
    description: 'Đạt cảnh giới Nguyên Anh.',
    category: 'cultivation',
    tier: 'platinum',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 28,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 20_000, exp: 10_000 },
    hidden: false,
  },
  {
    key: 'cultivate_24_hours',
    nameVi: 'Tu Luyện Nhất Nhật',
    nameEn: 'One-Day Cultivator',
    description: 'Tu luyện tổng cộng 24 giờ (86400 giây).',
    category: 'cultivation',
    tier: 'silver',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 86_400,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_000, exp: 500 },
    hidden: false,
  },
  {
    key: 'cultivate_30_days',
    nameVi: 'Tu Luyện Tam Tuần',
    nameEn: 'Thirty-Day Cultivator',
    description: 'Tu luyện tổng cộng 30 ngày (2,592,000 giây).',
    category: 'cultivation',
    tier: 'gold',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 2_592_000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 8_000, exp: 4_000 },
    hidden: false,
  },

  // ===== EXPLORATION — 5 =====
  {
    key: 'first_dungeon_clear',
    nameVi: 'Sơ Đăng Bí Cảnh',
    nameEn: 'First Dungeon Clear',
    description: 'Bước chân đầu tiên vào bí cảnh.',
    category: 'exploration',
    tier: 'bronze',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 1,
    element: null,
    rewardTitleKey: 'achievement_first_dungeon',
    // Phase 11.10.F — second non-empty `reward.items` cho exploration
    // milestone. 3× tinh_thiet (ORE LINH) tiếp đường cho refine flow
    // (Phase 11.5.B `RefineService` cost). Khuyến khích player thử refine
    // sau dungeon đầu tiên.
    reward: {
      linhThach: 150,
      exp: 80,
      items: [{ itemKey: 'tinh_thiet', qty: 3 }],
    },
    hidden: false,
  },
  {
    key: 'clear_10_dungeons',
    nameVi: 'Thập Đại Bí Cảnh',
    nameEn: 'Ten Dungeons Conquered',
    description: 'Hoàn thành 10 bí cảnh.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 10,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_500, exp: 800 },
    hidden: false,
  },
  {
    key: 'clear_100_dungeons',
    nameVi: 'Bách Đại Bí Cảnh',
    nameEn: 'Hundred Dungeons Conquered',
    description: 'Hoàn thành 100 bí cảnh.',
    category: 'exploration',
    tier: 'gold',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 15_000, exp: 8_000 },
    hidden: false,
  },
  {
    key: 'clear_kim_dungeon',
    nameVi: 'Kim Sơn Mạch Khám Phá',
    nameEn: 'Kim Mountain Vein Explorer',
    description: 'Hoàn thành 5 bí cảnh hệ Kim.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 5,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_000, exp: 500 },
    hidden: false,
  },
  {
    key: 'clear_endgame_dungeon',
    nameVi: 'Cửu La Điện Đăng Đỉnh',
    nameEn: 'Cuu La Dien Conqueror',
    description: 'Hoàn thành dungeon endgame `cuu_la_dien` (single-boss).',
    category: 'exploration',
    tier: 'diamond',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 1,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 50_000, exp: 25_000 },
    hidden: true,
  },

  // ===== SOCIAL — 4 =====
  {
    key: 'first_sect_join',
    nameVi: 'Tông Môn Đăng Tịch',
    nameEn: 'Sect Initiate',
    description: 'Lần đầu gia nhập tông môn.',
    category: 'social',
    tier: 'bronze',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 1,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 100, exp: 50 },
    hidden: false,
  },
  {
    key: 'first_chat',
    nameVi: 'Khẩu Khai Chí Tôn',
    nameEn: 'First Words',
    description: 'Lần đầu gửi tin nhắn world chat.',
    category: 'social',
    tier: 'bronze',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 1,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 50 },
    hidden: false,
  },
  {
    key: 'sect_donate_1000',
    nameVi: 'Tông Môn Cống Hiến Tiểu Cấp',
    nameEn: 'Sect Patron',
    description: 'Cống hiến 1000 cho tông môn.',
    category: 'social',
    tier: 'silver',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 800, exp: 400 },
    hidden: false,
  },
  {
    key: 'sect_donate_10000',
    nameVi: 'Tông Môn Cống Hiến Đại Cấp',
    nameEn: 'Sect Benefactor',
    description: 'Cống hiến 10,000 cho tông môn.',
    category: 'social',
    tier: 'gold',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 10_000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 8_000, exp: 4_000 },
    hidden: false,
  },

  // ===== ECONOMY — 4 =====
  {
    key: 'first_market_buy',
    nameVi: 'Sơ Mua Hàng',
    nameEn: 'First Market Buy',
    description: 'Lần đầu mua một item từ market.',
    category: 'economy',
    tier: 'bronze',
    goalKind: 'BUY_LISTING',
    goalAmount: 1,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 50 },
    hidden: false,
  },
  {
    key: 'first_market_sell',
    nameVi: 'Sơ Bán Hàng',
    nameEn: 'First Market Sale',
    description: 'Lần đầu bán một item lên market.',
    category: 'economy',
    tier: 'bronze',
    goalKind: 'SELL_LISTING',
    goalAmount: 1,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 50 },
    hidden: false,
  },
  {
    key: 'market_buyer_100',
    nameVi: 'Bách Đại Thương Khách',
    nameEn: 'Veteran Buyer',
    description: 'Mua 100 item từ market.',
    category: 'economy',
    tier: 'silver',
    goalKind: 'BUY_LISTING',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 2_000, exp: 1_000 },
    hidden: false,
  },
  {
    key: 'market_seller_100',
    nameVi: 'Bách Đại Cửa Hiệu',
    nameEn: 'Veteran Seller',
    description: 'Bán 100 item lên market.',
    category: 'economy',
    tier: 'silver',
    goalKind: 'SELL_LISTING',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 2_000, exp: 1_000 },
    hidden: false,
  },

  // ===== MILESTONE — 3 =====
  {
    key: 'gain_exp_1000',
    nameVi: 'Sơ Thiêm Kinh Nghiệm',
    nameEn: 'First Milestone',
    description: 'Tích luỹ 1000 EXP.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'GAIN_EXP',
    goalAmount: 1_000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 100 },
    hidden: false,
  },
  {
    key: 'gain_exp_100000',
    nameVi: 'Bách Thiên Kinh Nghiệm',
    nameEn: 'Hundred-Thousand Mark',
    description: 'Tích luỹ 100,000 EXP.',
    category: 'milestone',
    tier: 'silver',
    goalKind: 'GAIN_EXP',
    goalAmount: 100_000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 3_000, exp: 1_500 },
    hidden: false,
  },
  {
    key: 'gain_exp_10million',
    nameVi: 'Thập Triệu Kinh Nghiệm',
    nameEn: 'Ten-Million Master',
    description: 'Tích luỹ 10,000,000 EXP.',
    category: 'milestone',
    tier: 'platinum',
    goalKind: 'GAIN_EXP',
    goalAmount: 10_000_000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 30_000, exp: 15_000 },
    hidden: false,
  },

  // ===== COLLECTION — 2 =====
  {
    key: 'collect_50_items_bought',
    nameVi: 'Sưu Tầm Tiểu Cấp',
    nameEn: 'Item Collector I',
    description: 'Mua tổng cộng 50 item từ market.',
    category: 'collection',
    tier: 'silver',
    goalKind: 'BUY_LISTING',
    goalAmount: 50,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1_500, exp: 800 },
    hidden: false,
  },
  {
    key: 'collect_500_items_bought',
    nameVi: 'Sưu Tầm Đại Cấp',
    nameEn: 'Item Collector II',
    description: 'Mua tổng cộng 500 item từ market.',
    category: 'collection',
    tier: 'gold',
    goalKind: 'BUY_LISTING',
    goalAmount: 500,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 8_000, exp: 4_000 },
    hidden: false,
  },

  // ===== ALCHEMY (Luyện Đan) — 2 (Phase 11.11.E) =====
  {
    key: 'pill_apprentice',
    nameVi: 'Đan Tu Nhập Môn',
    nameEn: 'Pill Apprentice',
    description: 'Luyện thành công 10 viên đan dược (bất kể phẩm bậc).',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 10,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 200, exp: 100 },
    hidden: false,
  },
  {
    key: 'pill_master',
    nameVi: 'Đan Tu Đại Sư',
    nameEn: 'Pill Master',
    description: 'Luyện thành công 100 viên đan dược tích luỹ.',
    category: 'milestone',
    tier: 'gold',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 5_000, exp: 2_000 },
    hidden: false,
  },
  {
    key: 'phase46_pet_bond_first',
    nameVi: 'Linh Thú Sơ Duyên',
    nameEn: 'First Spirit Beast Bond',
    description: 'Tích luỹ EXP đại diện cho duyên khởi linh thú ở foundation.',
    category: 'collection',
    tier: 'bronze',
    goalKind: 'GAIN_EXP',
    goalAmount: 5_000,
    element: null,
    rewardTitleKey: 'phase46_title_pet_bonder',
    reward: { linhThach: 300, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase46_boss_first_stand',
    nameVi: 'Đối Diện Yêu Vương',
    nameEn: 'First Stand Against a Boss',
    description: 'Chạm trán boss 5 lần, reward nhỏ để giữ nhịp hoạt động.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'BOSS_HIT',
    goalAmount: 5,
    element: null,
    rewardTitleKey: 'phase46_title_boss_watcher',
    reward: { linhThach: 800, exp: 300 },
    hidden: false,
  },
  {
    key: 'phase46_secret_realm_scout',
    nameVi: 'Bí Cảnh Tuần Du',
    nameEn: 'Secret Realm Scout',
    description: 'Hoàn thành 3 lượt bí cảnh/phó bản đầu tiên.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 3,
    element: null,
    rewardTitleKey: null,
    reward: { linhThach: 700, exp: 260 },
    hidden: false,
  },
  {
    key: 'phase46_fortuitous_sign',
    nameVi: 'Kỳ Ngộ Sơ Hiện',
    nameEn: 'First Fortuitous Sign',
    description: 'Ghi nhận 5 tương tác cộng đồng như dấu hiệu kỳ ngộ an toàn.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 5,
    element: null,
    rewardTitleKey: null,
    reward: { linhThach: 150 },
    hidden: true,
  },
  {
    key: 'phase46_sect_regular',
    nameVi: 'Tông Môn Thường Cần',
    nameEn: 'Steady Sect Regular',
    description: 'Tích luỹ 2.000 đóng góp tông môn.',
    category: 'social',
    tier: 'silver',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 2_000,
    element: null,
    rewardTitleKey: 'phase46_title_sect_regular',
    reward: { linhThach: 1_000, exp: 400 },
    hidden: false,
  },
  {
    key: 'phase46_event_participant',
    nameVi: 'Dấu Ấn Hội Mùa',
    nameEn: 'Seasonal Event Mark',
    description: 'Foundation event milestone, dùng EXP progress đến khi event hook riêng ổn định.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'GAIN_EXP',
    goalAmount: 20_000,
    element: null,
    rewardTitleKey: null,
    reward: { linhThach: 500, exp: 200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_033',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 033',
    nameEn: 'Phase 21 — Chapter 1 Deed 033',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'bronze',
    goalKind: 'KILL_MONSTER',
    goalAmount: 100,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_033',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_034',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 034',
    nameEn: 'Phase 21 — Chapter 2 Deed 034',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'silver',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 500,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_034',
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_035',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 035',
    nameEn: 'Phase 21 — Chapter 3 Deed 035',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'gold',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 1000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_035',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_036',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 036',
    nameEn: 'Phase 21 — Chapter 4 Deed 036',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'platinum',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 2000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_036',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_037',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 037',
    nameEn: 'Phase 21 — Chapter 5 Deed 037',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'diamond',
    goalKind: 'SELL_LISTING',
    goalAmount: 4000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_037',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_038',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 038',
    nameEn: 'Phase 21 — Chapter 6 Deed 038',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'GAIN_EXP',
    goalAmount: 100,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_038',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_039',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 039',
    nameEn: 'Phase 21 — Chapter 7 Deed 039',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'silver',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 500,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_039',
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_040',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 040',
    nameEn: 'Phase 21 — Chapter 8 Deed 040',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'gold',
    goalKind: 'BOSS_HIT',
    goalAmount: 1000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_040',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_041',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 041',
    nameEn: 'Phase 21 — Chapter 1 Deed 041',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'platinum',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 2000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_041',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_042',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 042',
    nameEn: 'Phase 21 — Chapter 2 Deed 042',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'diamond',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 4000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_042',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_043',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 043',
    nameEn: 'Phase 21 — Chapter 3 Deed 043',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'bronze',
    goalKind: 'BUY_LISTING',
    goalAmount: 100,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_043',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_044',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 044',
    nameEn: 'Phase 21 — Chapter 4 Deed 044',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 500,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_044',
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_045',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 045',
    nameEn: 'Phase 21 — Chapter 5 Deed 045',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'gold',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 1000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_045',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_046',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 046',
    nameEn: 'Phase 21 — Chapter 6 Deed 046',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'platinum',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 2000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_046',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_047',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 047',
    nameEn: 'Phase 21 — Chapter 7 Deed 047',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'diamond',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 4000,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_047',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_048',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 048',
    nameEn: 'Phase 21 — Chapter 8 Deed 048',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'bronze',
    goalKind: 'SELL_LISTING',
    goalAmount: 100,
    element: null,
    rewardTitleKey: 'phase21_title_achievement_048',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_049',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 049',
    nameEn: 'Phase 21 — Chapter 1 Deed 049',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'GAIN_EXP',
    goalAmount: 500,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_049',
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_050',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 050',
    nameEn: 'Phase 21 — Chapter 2 Deed 050',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'gold',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 1000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_050',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_051',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 051',
    nameEn: 'Phase 21 — Chapter 3 Deed 051',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'platinum',
    goalKind: 'BOSS_HIT',
    goalAmount: 2000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_051',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_052',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 052',
    nameEn: 'Phase 21 — Chapter 4 Deed 052',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'diamond',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_052',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_053',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 053',
    nameEn: 'Phase 21 — Chapter 5 Deed 053',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'bronze',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 100,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_053',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_054',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 054',
    nameEn: 'Phase 21 — Chapter 6 Deed 054',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'BUY_LISTING',
    goalAmount: 500,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_054',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_055',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 055',
    nameEn: 'Phase 21 — Chapter 7 Deed 055',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'gold',
    goalKind: 'KILL_MONSTER',
    goalAmount: 1000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_055',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_056',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 056',
    nameEn: 'Phase 21 — Chapter 8 Deed 056',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'platinum',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 2000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_056',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_057',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 057',
    nameEn: 'Phase 21 — Chapter 1 Deed 057',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'diamond',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_057',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_058',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 058',
    nameEn: 'Phase 21 — Chapter 2 Deed 058',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'bronze',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_058',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_059',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 059',
    nameEn: 'Phase 21 — Chapter 3 Deed 059',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'silver',
    goalKind: 'SELL_LISTING',
    goalAmount: 500,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_059',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_060',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 060',
    nameEn: 'Phase 21 — Chapter 4 Deed 060',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'gold',
    goalKind: 'GAIN_EXP',
    goalAmount: 1000,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_060',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_061',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 061',
    nameEn: 'Phase 21 — Chapter 5 Deed 061',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'platinum',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 2000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_061',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_062',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 062',
    nameEn: 'Phase 21 — Chapter 6 Deed 062',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'diamond',
    goalKind: 'BOSS_HIT',
    goalAmount: 4000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_062',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_063',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 063',
    nameEn: 'Phase 21 — Chapter 7 Deed 063',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'bronze',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_063',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_064',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 064',
    nameEn: 'Phase 21 — Chapter 8 Deed 064',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'silver',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 500,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_064',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_065',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 065',
    nameEn: 'Phase 21 — Chapter 1 Deed 065',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'gold',
    goalKind: 'BUY_LISTING',
    goalAmount: 1000,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_065',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_066',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 066',
    nameEn: 'Phase 21 — Chapter 2 Deed 066',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'platinum',
    goalKind: 'KILL_MONSTER',
    goalAmount: 2000,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_066',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_067',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 067',
    nameEn: 'Phase 21 — Chapter 3 Deed 067',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'diamond',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 4000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_067',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_068',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 068',
    nameEn: 'Phase 21 — Chapter 4 Deed 068',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'bronze',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 100,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_068',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_069',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 069',
    nameEn: 'Phase 21 — Chapter 5 Deed 069',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'silver',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 500,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_069',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_070',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 070',
    nameEn: 'Phase 21 — Chapter 6 Deed 070',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'gold',
    goalKind: 'SELL_LISTING',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_070',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_071',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 071',
    nameEn: 'Phase 21 — Chapter 7 Deed 071',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'platinum',
    goalKind: 'GAIN_EXP',
    goalAmount: 2000,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_071',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_072',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 072',
    nameEn: 'Phase 21 — Chapter 8 Deed 072',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'diamond',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 4000,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_072',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_073',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 073',
    nameEn: 'Phase 21 — Chapter 1 Deed 073',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'BOSS_HIT',
    goalAmount: 100,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_073',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_074',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 074',
    nameEn: 'Phase 21 — Chapter 2 Deed 074',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'silver',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 500,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_074',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_075',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 075',
    nameEn: 'Phase 21 — Chapter 3 Deed 075',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'gold',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_075',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_076',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 076',
    nameEn: 'Phase 21 — Chapter 4 Deed 076',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'platinum',
    goalKind: 'BUY_LISTING',
    goalAmount: 2000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_076',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_077',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 077',
    nameEn: 'Phase 21 — Chapter 5 Deed 077',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'diamond',
    goalKind: 'KILL_MONSTER',
    goalAmount: 4000,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_077',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_078',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 078',
    nameEn: 'Phase 21 — Chapter 6 Deed 078',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'bronze',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 100,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_078',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_079',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 079',
    nameEn: 'Phase 21 — Chapter 7 Deed 079',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'silver',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 500,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_079',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_080',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 080',
    nameEn: 'Phase 21 — Chapter 8 Deed 080',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'gold',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 1000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_080',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_081',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 081',
    nameEn: 'Phase 21 — Chapter 1 Deed 081',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'platinum',
    goalKind: 'SELL_LISTING',
    goalAmount: 2000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_081',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_082',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 082',
    nameEn: 'Phase 21 — Chapter 2 Deed 082',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'diamond',
    goalKind: 'GAIN_EXP',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_082',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_083',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 083',
    nameEn: 'Phase 21 — Chapter 3 Deed 083',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'bronze',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 100,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_083',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_084',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 084',
    nameEn: 'Phase 21 — Chapter 4 Deed 084',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'BOSS_HIT',
    goalAmount: 500,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_084',
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_085',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 085',
    nameEn: 'Phase 21 — Chapter 5 Deed 085',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'gold',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 1000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_085',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_086',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 086',
    nameEn: 'Phase 21 — Chapter 6 Deed 086',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'platinum',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 2000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_086',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_087',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 087',
    nameEn: 'Phase 21 — Chapter 7 Deed 087',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'diamond',
    goalKind: 'BUY_LISTING',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_087',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_088',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 088',
    nameEn: 'Phase 21 — Chapter 8 Deed 088',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'bronze',
    goalKind: 'KILL_MONSTER',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_088',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_089',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 089',
    nameEn: 'Phase 21 — Chapter 1 Deed 089',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'silver',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 500,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_089',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_090',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 090',
    nameEn: 'Phase 21 — Chapter 2 Deed 090',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'gold',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 1000,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_090',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_091',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 091',
    nameEn: 'Phase 21 — Chapter 3 Deed 091',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'platinum',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 2000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_091',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_092',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 092',
    nameEn: 'Phase 21 — Chapter 4 Deed 092',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'diamond',
    goalKind: 'SELL_LISTING',
    goalAmount: 4000,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_092',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_093',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 093',
    nameEn: 'Phase 21 — Chapter 5 Deed 093',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'bronze',
    goalKind: 'GAIN_EXP',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_093',
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_094',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 094',
    nameEn: 'Phase 21 — Chapter 6 Deed 094',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'silver',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 500,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_094',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_095',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 095',
    nameEn: 'Phase 21 — Chapter 7 Deed 095',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'gold',
    goalKind: 'BOSS_HIT',
    goalAmount: 1000,
    element: 'moc',
    rewardTitleKey: 'phase21_title_achievement_095',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_096',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 096',
    nameEn: 'Phase 21 — Chapter 8 Deed 096',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'platinum',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 2000,
    element: 'thuy',
    rewardTitleKey: 'phase21_title_achievement_096',
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_097',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 097',
    nameEn: 'Phase 21 — Chapter 1 Deed 097',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'diamond',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 4000,
    element: 'hoa',
    rewardTitleKey: 'phase21_title_achievement_097',
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_098',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 098',
    nameEn: 'Phase 21 — Chapter 2 Deed 098',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'bronze',
    goalKind: 'BUY_LISTING',
    goalAmount: 100,
    element: 'tho',
    rewardTitleKey: 'phase21_title_achievement_098',
    reward: { linhThach: 180, exp: 120 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_099',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 099',
    nameEn: 'Phase 21 — Chapter 3 Deed 099',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'silver',
    goalKind: 'KILL_MONSTER',
    goalAmount: 500,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_099',
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_100',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 100',
    nameEn: 'Phase 21 — Chapter 4 Deed 100',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'gold',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: 'phase21_title_achievement_100',
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_101',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 101',
    nameEn: 'Phase 21 — Chapter 5 Deed 101',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'platinum',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 2000,
    element: 'moc',
    rewardTitleKey: null,
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_102',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 102',
    nameEn: 'Phase 21 — Chapter 6 Deed 102',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'diamond',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 4000,
    element: 'thuy',
    rewardTitleKey: null,
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_103',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 103',
    nameEn: 'Phase 21 — Chapter 7 Deed 103',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'bronze',
    goalKind: 'SELL_LISTING',
    goalAmount: 100,
    element: 'hoa',
    rewardTitleKey: null,
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_104',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 104',
    nameEn: 'Phase 21 — Chapter 8 Deed 104',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'silver',
    goalKind: 'GAIN_EXP',
    goalAmount: 500,
    element: 'tho',
    rewardTitleKey: null,
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_105',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 105',
    nameEn: 'Phase 21 — Chapter 1 Deed 105',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'gold',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 1000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 1600, exp: 1200 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_106',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 106',
    nameEn: 'Phase 21 — Chapter 2 Deed 106',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'platinum',
    goalKind: 'BOSS_HIT',
    goalAmount: 2000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_107',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 107',
    nameEn: 'Phase 21 — Chapter 3 Deed 107',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'diamond',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 4000,
    element: 'moc',
    rewardTitleKey: null,
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_108',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 108',
    nameEn: 'Phase 21 — Chapter 4 Deed 108',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'bronze',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 100,
    element: 'thuy',
    rewardTitleKey: null,
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_109',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 109',
    nameEn: 'Phase 21 — Chapter 5 Deed 109',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'silver',
    goalKind: 'BUY_LISTING',
    goalAmount: 500,
    element: 'hoa',
    rewardTitleKey: null,
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_110',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 110',
    nameEn: 'Phase 21 — Chapter 6 Deed 110',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'gold',
    goalKind: 'KILL_MONSTER',
    goalAmount: 1000,
    element: 'tho',
    rewardTitleKey: null,
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_111',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 111',
    nameEn: 'Phase 21 — Chapter 7 Deed 111',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'platinum',
    goalKind: 'CULTIVATE_SECONDS',
    goalAmount: 2000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_112',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 112',
    nameEn: 'Phase 21 — Chapter 8 Deed 112',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'diamond',
    goalKind: 'CLEAR_DUNGEON',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 6000, exp: 5000 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_113',
    nameVi: 'Phase 21 — Hoa Thiên Tân Đồ 113',
    nameEn: 'Phase 21 — Chapter 1 Deed 113',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Tân Đồ, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'bronze',
    goalKind: 'CHAT_MESSAGE',
    goalAmount: 100,
    element: 'moc',
    rewardTitleKey: null,
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_114',
    nameVi: 'Phase 21 — Linh Căn Sơ Tỉnh 114',
    nameEn: 'Phase 21 — Chapter 2 Deed 114',
    description: 'Thành tựu Phase 21 cho chuỗi Linh Căn Sơ Tỉnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'economy',
    tier: 'silver',
    goalKind: 'SELL_LISTING',
    goalAmount: 500,
    element: 'thuy',
    rewardTitleKey: null,
    reward: { linhThach: 600, exp: 450 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_115',
    nameVi: 'Phase 21 — Ngoại Môn Trụ Cột 115',
    nameEn: 'Phase 21 — Chapter 3 Deed 115',
    description: 'Thành tựu Phase 21 cho chuỗi Ngoại Môn Trụ Cột, theo dõi hoạt động story mà không phá reward curve.',
    category: 'milestone',
    tier: 'gold',
    goalKind: 'GAIN_EXP',
    goalAmount: 1000,
    element: 'hoa',
    rewardTitleKey: null,
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_116',
    nameVi: 'Phase 21 — Bí Cảnh Khai Môn 116',
    nameEn: 'Phase 21 — Chapter 4 Deed 116',
    description: 'Thành tựu Phase 21 cho chuỗi Bí Cảnh Khai Môn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'collection',
    tier: 'platinum',
    goalKind: 'ALCHEMY_CRAFT',
    goalAmount: 2000,
    element: 'tho',
    rewardTitleKey: null,
    reward: { linhThach: 3200, exp: 2600 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_117',
    nameVi: 'Phase 21 — Ma Đạo Thẩm Vấn 117',
    nameEn: 'Phase 21 — Chapter 5 Deed 117',
    description: 'Thành tựu Phase 21 cho chuỗi Ma Đạo Thẩm Vấn, theo dõi hoạt động story mà không phá reward curve.',
    category: 'combat',
    tier: 'diamond',
    goalKind: 'BOSS_HIT',
    goalAmount: 4000,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 6000, exp: 5000 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_118',
    nameVi: 'Phase 21 — Ngũ Hành Thiên Mệnh 118',
    nameEn: 'Phase 21 — Chapter 6 Deed 118',
    description: 'Thành tựu Phase 21 cho chuỗi Ngũ Hành Thiên Mệnh, theo dõi hoạt động story mà không phá reward curve.',
    category: 'cultivation',
    tier: 'bronze',
    goalKind: 'SECT_CONTRIBUTE',
    goalAmount: 100,
    element: 'kim',
    rewardTitleKey: null,
    reward: { linhThach: 180, exp: 120 },
    hidden: false,
  },
  {
    key: 'phase21_achievement_119',
    nameVi: 'Phase 21 — Thanh Tâm Hộ Đạo 119',
    nameEn: 'Phase 21 — Chapter 7 Deed 119',
    description: 'Thành tựu Phase 21 cho chuỗi Thanh Tâm Hộ Đạo, theo dõi hoạt động story mà không phá reward curve.',
    category: 'exploration',
    tier: 'silver',
    goalKind: 'BREAKTHROUGH',
    goalAmount: 500,
    element: 'moc',
    rewardTitleKey: null,
    reward: { linhThach: 600, exp: 450 },
    hidden: true,
  },
  {
    key: 'phase21_achievement_120',
    nameVi: 'Phase 21 — Hoa Thiên Hộ Pháp 120',
    nameEn: 'Phase 21 — Chapter 8 Deed 120',
    description: 'Thành tựu Phase 21 cho chuỗi Hoa Thiên Hộ Pháp, theo dõi hoạt động story mà không phá reward curve.',
    category: 'social',
    tier: 'gold',
    goalKind: 'BUY_LISTING',
    goalAmount: 1000,
    element: 'thuy',
    rewardTitleKey: null,
    reward: { linhThach: 1600, exp: 1200 },
    hidden: false,
  }];

const ACHIEVEMENTS_BY_KEY = new Map<string, AchievementDef>(
  ACHIEVEMENTS.map((a) => [a.key, a])
);

/**
 * Lookup achievement by key.
 */
export function getAchievementDef(key: string): AchievementDef | undefined {
  return ACHIEVEMENTS_BY_KEY.get(key);
}

/**
 * Filter theo category.
 */
export function achievementsByCategory(
  category: AchievementCategory
): readonly AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => a.category === category);
}

/**
 * Filter theo tier.
 */
export function achievementsByTier(
  tier: AchievementTier
): readonly AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => a.tier === tier);
}

/**
 * Filter theo goalKind (Phase 11.10.B service event listener routing).
 */
export function achievementsByGoalKind(
  goalKind: MissionGoalKind
): readonly AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => a.goalKind === goalKind);
}

/**
 * Filter theo element (null = neutral).
 */
export function achievementsByElement(
  element: ElementKey | null
): readonly AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => a.element === element);
}

/**
 * Filter visible (non-hidden).
 */
export function visibleAchievements(): readonly AchievementDef[] {
  return ACHIEVEMENTS.filter((a) => !a.hidden);
}
