import type { QuestDef, QuestRewardDef, QuestStepDef } from './quests';

interface Phase21BranchQuestInput { key: string; name: string; description: string; realmKey: string; requiredRealmOrder: number; giverNpcKey: string; chapterKey: string; chainKey: string; prerequisiteQuestKey: string; objective: string; requirement: string; trigger: string; steps: readonly QuestStepDef[]; rewards: QuestRewardDef; loreSummary: string; }
function branchQuest(input: Phase21BranchQuestInput): QuestDef { return { ...input, kind: 'branch' }; }
export const PHASE21_BRANCH_QUESTS: readonly QuestDef[] = [
  branchQuest({
    key: 'phase21_branch_001',
    name: 'Phàm Nhân Nhập Đạo: Nhánh lương khô tân đệ tử 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lương khô tân đệ tử bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_1', prerequisiteQuestKey: 'phase21_ch01_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về lương khô tân đệ tử.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=lương khô tân đệ tử',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 63, exp: 138, congHien: 10, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lương khô tân đệ tử; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_002',
    name: 'Phàm Nhân Nhập Đạo: Nhánh Sơn Cốc bất ổn 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Sơn Cốc bất ổn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_2', prerequisiteQuestKey: 'phase21_ch01_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về Sơn Cốc bất ổn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=Sơn Cốc bất ổn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 66, exp: 146, congHien: 10, affinity: [{ npcKey: 'npc_a_linh', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Sơn Cốc bất ổn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_003',
    name: 'Phàm Nhân Nhập Đạo: Nhánh đời sống ngoại môn 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đời sống ngoại môn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_3', prerequisiteQuestKey: 'phase21_ch01_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về đời sống ngoại môn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=đời sống ngoại môn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 67, exp: 154, congHien: 11, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đời sống ngoại môn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_004',
    name: 'Phàm Nhân Nhập Đạo: Nhánh đèn tổ sư 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đèn tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_0', prerequisiteQuestKey: 'phase21_ch01_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về đèn tổ sư.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=đèn tổ sư',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 70, exp: 162, congHien: 11, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đèn tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_005',
    name: 'Phàm Nhân Nhập Đạo: Nhánh lương khô tân đệ tử 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lương khô tân đệ tử bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_1', prerequisiteQuestKey: 'phase21_ch01_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về lương khô tân đệ tử.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=lương khô tân đệ tử',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 71, exp: 170, congHien: 12, affinity: [{ npcKey: 'npc_a_linh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lương khô tân đệ tử; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_006',
    name: 'Phàm Nhân Nhập Đạo: Nhánh Sơn Cốc bất ổn 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Sơn Cốc bất ổn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_2', prerequisiteQuestKey: 'phase21_ch01_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về Sơn Cốc bất ổn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=Sơn Cốc bất ổn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 74, exp: 178, congHien: 13, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Sơn Cốc bất ổn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_007',
    name: 'Phàm Nhân Nhập Đạo: Nhánh đời sống ngoại môn 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đời sống ngoại môn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_3', prerequisiteQuestKey: 'phase21_ch01_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về đời sống ngoại môn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=đời sống ngoại môn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 75, exp: 186, congHien: 14, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đời sống ngoại môn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_008',
    name: 'Phàm Nhân Nhập Đạo: Nhánh đèn tổ sư 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đèn tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_branch_ch01_0', prerequisiteQuestKey: 'phase21_ch01_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về đèn tổ sư.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_pham_nhan_nhap_dao; theme=đèn tổ sư',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch1_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 78, exp: 194, congHien: 14, affinity: [{ npcKey: 'npc_a_linh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đèn tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_009',
    name: 'Linh Căn Thức Tỉnh: Nhánh Tịch Linh vết mờ 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Linh vết mờ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_1', prerequisiteQuestKey: 'phase21_ch02_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Linh vết mờ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=Tịch Linh vết mờ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 84, exp: 202, congHien: 13, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Linh vết mờ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_010',
    name: 'Linh Căn Thức Tỉnh: Nhánh lò đan thiếu dược 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lò đan thiếu dược bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_2', prerequisiteQuestKey: 'phase21_ch02_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về lò đan thiếu dược.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=lò đan thiếu dược',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 86, exp: 210, congHien: 14, affinity: [{ npcKey: 'npc_a_linh', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lò đan thiếu dược; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_011',
    name: 'Linh Căn Thức Tỉnh: Nhánh linh căn lệch nhịp 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý linh căn lệch nhịp bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_3', prerequisiteQuestKey: 'phase21_ch02_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về linh căn lệch nhịp.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=linh căn lệch nhịp',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 88, exp: 218, congHien: 14, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với linh căn lệch nhịp; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_012',
    name: 'Linh Căn Thức Tỉnh: Nhánh Ngũ Hành sơ cảm 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Ngũ Hành sơ cảm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_0', prerequisiteQuestKey: 'phase21_ch02_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về Ngũ Hành sơ cảm.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=Ngũ Hành sơ cảm',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 90, exp: 226, congHien: 15, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Ngũ Hành sơ cảm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_013',
    name: 'Linh Căn Thức Tỉnh: Nhánh Tịch Linh vết mờ 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Linh vết mờ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_1', prerequisiteQuestKey: 'phase21_ch02_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Linh vết mờ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=Tịch Linh vết mờ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 92, exp: 234, congHien: 16, affinity: [{ npcKey: 'npc_a_linh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Linh vết mờ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_014',
    name: 'Linh Căn Thức Tỉnh: Nhánh lò đan thiếu dược 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lò đan thiếu dược bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_2', prerequisiteQuestKey: 'phase21_ch02_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về lò đan thiếu dược.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=lò đan thiếu dược',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 94, exp: 242, congHien: 16, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lò đan thiếu dược; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_015',
    name: 'Linh Căn Thức Tỉnh: Nhánh linh căn lệch nhịp 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý linh căn lệch nhịp bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_3', prerequisiteQuestKey: 'phase21_ch02_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về linh căn lệch nhịp.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=linh căn lệch nhịp',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 96, exp: 251, congHien: 17, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với linh căn lệch nhịp; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_016',
    name: 'Linh Căn Thức Tỉnh: Nhánh Ngũ Hành sơ cảm 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Ngũ Hành sơ cảm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_branch_ch02_0', prerequisiteQuestKey: 'phase21_ch02_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về Ngũ Hành sơ cảm.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_linh_can_thuc_tinh; theme=Ngũ Hành sơ cảm',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch2_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_a_linh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 98, exp: 259, congHien: 18, affinity: [{ npcKey: 'npc_a_linh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Ngũ Hành sơ cảm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_017',
    name: 'Tông Môn Sơ Khởi: Nhánh Vạn Bảo giao kèo 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Vạn Bảo giao kèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_1', prerequisiteQuestKey: 'phase21_ch03_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về Vạn Bảo giao kèo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=Vạn Bảo giao kèo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 104, exp: 266, congHien: 16, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Vạn Bảo giao kèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_018',
    name: 'Tông Môn Sơ Khởi: Nhánh trận kỳ cũ 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý trận kỳ cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_van_kim_nuong', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_2', prerequisiteQuestKey: 'phase21_ch03_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về trận kỳ cũ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=trận kỳ cũ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_van_kim_nuong', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 106, exp: 274, congHien: 17, affinity: [{ npcKey: 'npc_van_kim_nuong', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với trận kỳ cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_019',
    name: 'Tông Môn Sơ Khởi: Nhánh tông môn nghèo 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý tông môn nghèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_3', prerequisiteQuestKey: 'phase21_ch03_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về tông môn nghèo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=tông môn nghèo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 108, exp: 283, congHien: 18, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với tông môn nghèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_020',
    name: 'Tông Môn Sơ Khởi: Nhánh Hàn Dạ khiêu chiến 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Hàn Dạ khiêu chiến bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_0', prerequisiteQuestKey: 'phase21_ch03_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về Hàn Dạ khiêu chiến.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=Hàn Dạ khiêu chiến',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 110, exp: 291, congHien: 18, affinity: [{ npcKey: 'npc_han_da', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Hàn Dạ khiêu chiến; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_021',
    name: 'Tông Môn Sơ Khởi: Nhánh Vạn Bảo giao kèo 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Vạn Bảo giao kèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_1', prerequisiteQuestKey: 'phase21_ch03_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về Vạn Bảo giao kèo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=Vạn Bảo giao kèo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 112, exp: 299, congHien: 19, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Vạn Bảo giao kèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_022',
    name: 'Tông Môn Sơ Khởi: Nhánh trận kỳ cũ 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý trận kỳ cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_van_kim_nuong', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_2', prerequisiteQuestKey: 'phase21_ch03_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về trận kỳ cũ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=trận kỳ cũ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_van_kim_nuong', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 114, exp: 307, congHien: 20, affinity: [{ npcKey: 'npc_van_kim_nuong', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với trận kỳ cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_023',
    name: 'Tông Môn Sơ Khởi: Nhánh tông môn nghèo 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý tông môn nghèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_3', prerequisiteQuestKey: 'phase21_ch03_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về tông môn nghèo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=tông môn nghèo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 116, exp: 315, congHien: 21, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với tông môn nghèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_024',
    name: 'Tông Môn Sơ Khởi: Nhánh Hàn Dạ khiêu chiến 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Hàn Dạ khiêu chiến bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_branch_ch03_0', prerequisiteQuestKey: 'phase21_ch03_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về Hàn Dạ khiêu chiến.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tong_mon_so_khoi; theme=Hàn Dạ khiêu chiến',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch3_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 118, exp: 324, congHien: 21, affinity: [{ npcKey: 'npc_han_da', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Hàn Dạ khiêu chiến; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_025',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh ký ức tổ sư 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ký ức tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_1', prerequisiteQuestKey: 'phase21_ch04_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về ký ức tổ sư.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=ký ức tổ sư',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 125, exp: 331, congHien: 20, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ký ức tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_026',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh dấu phong ấn 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý dấu phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_2', prerequisiteQuestKey: 'phase21_ch04_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về dấu phong ấn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=dấu phong ấn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 126, exp: 339, congHien: 21, affinity: [{ npcKey: 'npc_han_da', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với dấu phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_027',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh trăng máu còn sót 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý trăng máu còn sót bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_3', prerequisiteQuestKey: 'phase21_ch04_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về trăng máu còn sót.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=trăng máu còn sót',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 129, exp: 347, congHien: 21, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với trăng máu còn sót; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_028',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh giếng cổ đổi màu 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý giếng cổ đổi màu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_0', prerequisiteQuestKey: 'phase21_ch04_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về giếng cổ đổi màu.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=giếng cổ đổi màu',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 130, exp: 356, congHien: 22, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với giếng cổ đổi màu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_029',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh ký ức tổ sư 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ký ức tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_1', prerequisiteQuestKey: 'phase21_ch04_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về ký ức tổ sư.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=ký ức tổ sư',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 133, exp: 364, congHien: 22, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ký ức tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_030',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh dấu phong ấn 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý dấu phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_2', prerequisiteQuestKey: 'phase21_ch04_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về dấu phong ấn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=dấu phong ấn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 134, exp: 372, congHien: 23, affinity: [{ npcKey: 'npc_han_da', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với dấu phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_031',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh trăng máu còn sót 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý trăng máu còn sót bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_3', prerequisiteQuestKey: 'phase21_ch04_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về trăng máu còn sót.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=trăng máu còn sót',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 137, exp: 380, congHien: 24, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với trăng máu còn sót; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_032',
    name: 'Bí Cảnh Huyết Nguyệt: Nhánh giếng cổ đổi màu 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý giếng cổ đổi màu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_branch_ch04_0', prerequisiteQuestKey: 'phase21_ch04_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về giếng cổ đổi màu.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_bi_canh_huyet_nguyet; theme=giếng cổ đổi màu',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch4_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 138, exp: 388, congHien: 25, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với giếng cổ đổi màu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_033',
    name: 'Ma Tu Xuất Thế: Nhánh đạo tâm lựa chọn 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đạo tâm lựa chọn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_1', prerequisiteQuestKey: 'phase21_ch05_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về đạo tâm lựa chọn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=đạo tâm lựa chọn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 145, exp: 396, congHien: 23, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đạo tâm lựa chọn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_034',
    name: 'Ma Tu Xuất Thế: Nhánh huyết khí mất kiểm 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý huyết khí mất kiểm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_ha_su_gia', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_2', prerequisiteQuestKey: 'phase21_ch05_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về huyết khí mất kiểm.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=huyết khí mất kiểm',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_ha_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 147, exp: 404, congHien: 24, affinity: [{ npcKey: 'npc_huyet_ha_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với huyết khí mất kiểm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_035',
    name: 'Ma Tu Xuất Thế: Nhánh Huyết Hà nhân chứng 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Huyết Hà nhân chứng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_3', prerequisiteQuestKey: 'phase21_ch05_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về Huyết Hà nhân chứng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=Huyết Hà nhân chứng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 149, exp: 412, congHien: 25, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Huyết Hà nhân chứng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_036',
    name: 'Ma Tu Xuất Thế: Nhánh ma tu bị oan 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ma tu bị oan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_0', prerequisiteQuestKey: 'phase21_ch05_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về ma tu bị oan.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=ma tu bị oan',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 151, exp: 420, congHien: 25, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ma tu bị oan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_037',
    name: 'Ma Tu Xuất Thế: Nhánh đạo tâm lựa chọn 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đạo tâm lựa chọn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_1', prerequisiteQuestKey: 'phase21_ch05_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về đạo tâm lựa chọn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=đạo tâm lựa chọn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 153, exp: 429, congHien: 26, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đạo tâm lựa chọn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_038',
    name: 'Ma Tu Xuất Thế: Nhánh huyết khí mất kiểm 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý huyết khí mất kiểm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_ha_su_gia', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_2', prerequisiteQuestKey: 'phase21_ch05_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về huyết khí mất kiểm.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=huyết khí mất kiểm',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_ha_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 155, exp: 437, congHien: 26, affinity: [{ npcKey: 'npc_huyet_ha_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với huyết khí mất kiểm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_039',
    name: 'Ma Tu Xuất Thế: Nhánh Huyết Hà nhân chứng 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Huyết Hà nhân chứng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_3', prerequisiteQuestKey: 'phase21_ch05_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về Huyết Hà nhân chứng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=Huyết Hà nhân chứng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 157, exp: 445, congHien: 27, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Huyết Hà nhân chứng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_040',
    name: 'Ma Tu Xuất Thế: Nhánh ma tu bị oan 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ma tu bị oan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_branch_ch05_0', prerequisiteQuestKey: 'phase21_ch05_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về ma tu bị oan.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ma_tu_xuat_the; theme=ma tu bị oan',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch5_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 159, exp: 453, congHien: 28, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ma tu bị oan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_041',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh Tịch Thiên tín hiệu 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Thiên tín hiệu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_1', prerequisiteQuestKey: 'phase21_ch06_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Thiên tín hiệu.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=Tịch Thiên tín hiệu',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 166, exp: 460, congHien: 26, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Thiên tín hiệu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_042',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh đồng đội hợp lực 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đồng đội hợp lực bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_2', prerequisiteQuestKey: 'phase21_ch06_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về đồng đội hợp lực.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=đồng đội hợp lực',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 167, exp: 469, congHien: 27, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đồng đội hợp lực; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_043',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh Ngũ Hành cộng hưởng 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Ngũ Hành cộng hưởng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_3', prerequisiteQuestKey: 'phase21_ch06_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về Ngũ Hành cộng hưởng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=Ngũ Hành cộng hưởng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 170, exp: 477, congHien: 28, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Ngũ Hành cộng hưởng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_044',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh đàn tế Kim Đan 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đàn tế Kim Đan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_0', prerequisiteQuestKey: 'phase21_ch06_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về đàn tế Kim Đan.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=đàn tế Kim Đan',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 171, exp: 485, congHien: 29, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đàn tế Kim Đan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_045',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh Tịch Thiên tín hiệu 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Thiên tín hiệu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_1', prerequisiteQuestKey: 'phase21_ch06_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Thiên tín hiệu.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=Tịch Thiên tín hiệu',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 174, exp: 493, congHien: 30, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Thiên tín hiệu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_046',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh đồng đội hợp lực 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đồng đội hợp lực bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_2', prerequisiteQuestKey: 'phase21_ch06_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về đồng đội hợp lực.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=đồng đội hợp lực',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 175, exp: 501, congHien: 30, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đồng đội hợp lực; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_047',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh Ngũ Hành cộng hưởng 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Ngũ Hành cộng hưởng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_3', prerequisiteQuestKey: 'phase21_ch06_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về Ngũ Hành cộng hưởng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=Ngũ Hành cộng hưởng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 178, exp: 510, congHien: 30, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Ngũ Hành cộng hưởng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_048',
    name: 'Ngũ Hành Thiên Mệnh: Nhánh đàn tế Kim Đan 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đàn tế Kim Đan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_branch_ch06_0', prerequisiteQuestKey: 'phase21_ch06_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về đàn tế Kim Đan.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_ngu_hanh_thien_menh; theme=đàn tế Kim Đan',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch6_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 179, exp: 518, congHien: 31, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đàn tế Kim Đan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_049',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh ký ức bị khoá 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ký ức bị khoá bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_1', prerequisiteQuestKey: 'phase21_ch07_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về ký ức bị khoá.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=ký ức bị khoá',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 186, exp: 525, congHien: 30, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ký ức bị khoá; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_050',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh lời thề hộ đạo 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lời thề hộ đạo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_2', prerequisiteQuestKey: 'phase21_ch07_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về lời thề hộ đạo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=lời thề hộ đạo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 188, exp: 533, congHien: 30, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lời thề hộ đạo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_051',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh tâm ma Mộc Thanh Y 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý tâm ma Mộc Thanh Y bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_3', prerequisiteQuestKey: 'phase21_ch07_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về tâm ma Mộc Thanh Y.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=tâm ma Mộc Thanh Y',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 190, exp: 542, congHien: 31, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với tâm ma Mộc Thanh Y; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_052',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh Tịch Linh Chủng 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Linh Chủng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_0', prerequisiteQuestKey: 'phase21_ch07_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Linh Chủng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=Tịch Linh Chủng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 192, exp: 550, congHien: 32, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Linh Chủng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_053',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh ký ức bị khoá 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý ký ức bị khoá bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_1', prerequisiteQuestKey: 'phase21_ch07_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về ký ức bị khoá.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=ký ức bị khoá',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 194, exp: 558, congHien: 33, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với ký ức bị khoá; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_054',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh lời thề hộ đạo 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý lời thề hộ đạo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_2', prerequisiteQuestKey: 'phase21_ch07_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về lời thề hộ đạo.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=lời thề hộ đạo',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 196, exp: 566, congHien: 34, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với lời thề hộ đạo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_055',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh tâm ma Mộc Thanh Y 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý tâm ma Mộc Thanh Y bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_3', prerequisiteQuestKey: 'phase21_ch07_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về tâm ma Mộc Thanh Y.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=tâm ma Mộc Thanh Y',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 198, exp: 574, congHien: 34, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với tâm ma Mộc Thanh Y; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_056',
    name: 'Tâm Ma Của Đại Sư Tỷ: Nhánh Tịch Linh Chủng 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Tịch Linh Chủng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_branch_ch07_0', prerequisiteQuestKey: 'phase21_ch07_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về Tịch Linh Chủng.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_tam_ma_dai_su_ty; theme=Tịch Linh Chủng',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch7_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 200, exp: 582, congHien: 34, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Tịch Linh Chủng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_057',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh kinh lâu cũ 1',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý kinh lâu cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_hoa_thien_dao_to', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_1', prerequisiteQuestKey: 'phase21_ch08_main_03',
    objective: 'Hoàn thành lựa chọn nhánh về kinh lâu cũ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=kinh lâu cũ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_1', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_hoa_thien_dao_to', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 206, exp: 590, congHien: 34, affinity: [{ npcKey: 'npc_hoa_thien_dao_to', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với kinh lâu cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_058',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh sứ giả Tịch Thiên 2',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý sứ giả Tịch Thiên bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_2', prerequisiteQuestKey: 'phase21_ch08_main_05',
    objective: 'Hoàn thành lựa chọn nhánh về sứ giả Tịch Thiên.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=sứ giả Tịch Thiên',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_2', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 208, exp: 598, congHien: 34, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với sứ giả Tịch Thiên; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_059',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh Hoa Thiên Sơn phong ấn 3',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Hoa Thiên Sơn phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_3', prerequisiteQuestKey: 'phase21_ch08_main_07',
    objective: 'Hoàn thành lựa chọn nhánh về Hoa Thiên Sơn phong ấn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=Hoa Thiên Sơn phong ấn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_3', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 210, exp: 606, congHien: 34, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Hoa Thiên Sơn phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_060',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh đạo thống tầng một 4',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đạo thống tầng một bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_hoa_thien_dao_to', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_0', prerequisiteQuestKey: 'phase21_ch08_main_09',
    objective: 'Hoàn thành lựa chọn nhánh về đạo thống tầng một.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=đạo thống tầng một',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_4', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_hoa_thien_dao_to', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 212, exp: 614, congHien: 35, affinity: [{ npcKey: 'npc_hoa_thien_dao_to', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đạo thống tầng một; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_061',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh kinh lâu cũ 5',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý kinh lâu cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_1', prerequisiteQuestKey: 'phase21_ch08_main_11',
    objective: 'Hoàn thành lựa chọn nhánh về kinh lâu cũ.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=kinh lâu cũ',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_5', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 214, exp: 622, congHien: 36, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với kinh lâu cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_062',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh sứ giả Tịch Thiên 6',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý sứ giả Tịch Thiên bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_2', prerequisiteQuestKey: 'phase21_ch08_main_13',
    objective: 'Hoàn thành lựa chọn nhánh về sứ giả Tịch Thiên.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=sứ giả Tịch Thiên',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_6', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 216, exp: 630, congHien: 37, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với sứ giả Tịch Thiên; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_063',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh Hoa Thiên Sơn phong ấn 7',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý Hoa Thiên Sơn phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_hoa_thien_dao_to', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_3', prerequisiteQuestKey: 'phase21_ch08_main_15',
    objective: 'Hoàn thành lựa chọn nhánh về Hoa Thiên Sơn phong ấn.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=Hoa Thiên Sơn phong ấn',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_7', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_hoa_thien_dao_to', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 218, exp: 638, congHien: 38, affinity: [{ npcKey: 'npc_hoa_thien_dao_to', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với Hoa Thiên Sơn phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  branchQuest({
    key: 'phase21_branch_064',
    name: 'Hoa Thiên Sơn Tầng Một: Nhánh đạo thống tầng một 8',
    description: 'Branch quest mở khi choice/affinity/sect/elemental hook, xử lý đạo thống tầng một bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_branch_ch08_0', prerequisiteQuestKey: 'phase21_ch08_main_02',
    objective: 'Hoàn thành lựa chọn nhánh về đạo thống tầng một.', requirement: 'Cần choice/affinity/sect/elemental hook và tiến trình chương tương ứng.',
    trigger: 'choice/affinity/sect/elemental hook; chapter=chapter_hoa_thien_son_tang_mot; theme=đạo thống tầng một',
    steps: [{ id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_branch_ch8_8', count: 1, description: 'Chọn hướng xử lý nhánh theo đạo tâm, tông môn hoặc affinity.' }, { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_tich_linh_su_gia', count: 1, description: 'Xác nhận hậu quả lựa chọn với NPC liên quan.' }],
    rewards: { linhThach: 220, exp: 646, congHien: 38, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Branch content gắn với đạo thống tầng một; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
];
