import type { QuestDef, QuestRewardDef, QuestStepDef } from './quests';

interface Phase21SideQuestInput {
  key: string;
  name: string;
  description: string;
  realmKey: string;
  requiredRealmOrder: number;
  giverNpcKey: string;
  chapterKey: string;
  chainKey: string;
  prerequisiteQuestKey: string;
  objective: string;
  requirement: string;
  startNpcKey?: string;
  endNpcKey?: string;
  steps: readonly QuestStepDef[];
  rewards: QuestRewardDef;
  loreSummary: string;
}

function sideQuest(input: Phase21SideQuestInput): QuestDef {
  return {
    ...input,
    kind: 'side',
    startNpcKey: input.startNpcKey ?? input.giverNpcKey,
    endNpcKey: input.endNpcKey ?? input.giverNpcKey,
  };
}

export const PHASE21_SIDE_QUESTS: readonly QuestDef[] = [
  sideQuest({
    key: 'phase21_side_001',
    name: 'Bát Cháo Ngoại Môn',
    description:
      'Một đệ tử mới nhịn ăn để đổi linh thạch mua hương cho cha mẹ; Mộc Thanh Y nhờ người chơi giúp mà không làm hắn mất mặt.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_side_outer_care',
    prerequisiteQuestKey: 'phase21_ch01_main_02',
    objective: 'Chuẩn bị thuốc và thức ăn cho đệ tử ngoại môn kiệt sức.',
    requirement: 'Gặp Mộc Thanh Y trong chương Phàm Nhân Nhập Đạo.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 2, description: 'Hái 2 Linh Thảo nấu cháo thuốc.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Giao lại cho Mộc Thanh Y để nàng âm thầm giúp đệ tử.' },
    ],
    rewards: { linhThach: 70, exp: 120, congHien: 12, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'Shows Hoa Thiên poverty and Mộc Thanh Y’s strict kindness.',
  }),
  sideQuest({
    key: 'phase21_side_002',
    name: 'Đèn Tàn Trước Điện',
    description:
      'Lăng Vân Sinh giữ một ngọn đèn tổ sư gần tắt; dầu đèn thiếu không đáng sợ bằng việc đệ tử quên vì ai mà tông môn còn tồn tại.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_side_sect_memory',
    prerequisiteQuestKey: 'phase21_ch01_main_01',
    objective: 'Tìm vật dẫn linh khí để giữ đèn tổ sư qua đêm.',
    requirement: 'Đã nhập Hoa Thiên Môn.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Tìm 1 Phù Vân Ngọc làm tim đèn tạm.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_keep_ancestral_lamp', count: 1, description: 'Chọn thắp đèn trước điện hay đem về kho trận.' },
    ],
    rewards: { linhThach: 80, exp: 140, congHien: 15, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'Small sect-memory quest that reinforces Hoa Thiên continuity.',
  }),
  sideQuest({
    key: 'phase21_side_003',
    name: 'Sổ Nợ Linh Điền',
    description:
      'Linh điền cũ ghi nợ nhiều đời đệ tử; từng dòng nợ là tên người đã rời núi hoặc chết trong bí cảnh.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_side_outer_care',
    prerequisiteQuestKey: 'phase21_ch01_main_03',
    objective: 'Kiểm kê linh điền để tách nợ thật khỏi vết cắn yêu thú.',
    requirement: 'Đã tuần tra Sơn Cốc đêm đầu.',
    steps: [
      { id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tới linh điền cũ phía Sơn Cốc.' },
      { id: 'step_02', kind: 'kill', targetType: 'monster', targetId: 'son_thu_lon', count: 3, description: 'Đuổi 3 Sơn Thử Lớn khỏi bờ ruộng.' },
    ],
    rewards: { linhThach: 90, exp: 160, congHien: 18, items: [{ itemKey: 'linh_lo_dan', qty: 1 }] },
    loreSummary: 'Grounds early economy and cultivation poverty in a human ledger.',
  }),
  sideQuest({
    key: 'phase21_side_004',
    name: 'Vỏ Kiếm Mượn Tạm',
    description:
      'So Kiếm mới nhận không có vỏ tốt; một thanh kiếm không vỏ dễ làm bị thương đồng môn trước khi làm bị thương yêu thú.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_side_new_disciple_path',
    prerequisiteQuestKey: 'phase21_ch01_main_05',
    objective: 'Rèn vỏ kiếm thô cho tân đệ tử.',
    requirement: 'Đã hoàn thành Mầm Không Tên.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 2, description: 'Thu 2 Tinh Thiết làm nẹp vỏ kiếm.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_plain_sword_sheath', count: 1, description: 'Chọn khắc tên bản thân hay khắc Hoa Thiên lên vỏ kiếm.' },
    ],
    rewards: { linhThach: 100, exp: 180, congHien: 20, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'Completes a small equipment-care beat for the new-player path.',
  }),
  sideQuest({
    key: 'phase21_side_005',
    name: 'Mảnh Bùa Dưới Suối',
    description:
      'Một mảnh bùa cũ trôi từ Linh Tuyền xuống Sơn Cốc; chữ trên đó giống nét viết của đời chưởng môn trước.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_side_sect_memory',
    prerequisiteQuestKey: 'phase21_ch01_main_04',
    objective: 'Thu hồi mảnh bùa để đối chiếu lịch sử Hoa Thiên.',
    requirement: 'Đã phát hiện sợi khí xám.',
    steps: [
      { id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm đoạn suối có phù văn trôi qua.' },
      { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Dùng Phù Vân Ngọc giữ mảnh bùa khỏi tan.' },
    ],
    rewards: { linhThach: 95, exp: 170, congHien: 18, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'Foreshadows erased Hoa Thiên records before Blood Moon.',
  }),
  sideQuest({
    key: 'phase21_side_006',
    name: 'Linh Căn Không Sáng',
    description:
      'Một đệ tử thất vọng vì linh căn yếu; Mộc Thanh Y muốn chứng minh ánh sáng đo linh căn không đo được đạo tâm.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_side_ling_root',
    prerequisiteQuestKey: 'phase21_ch02_main_01',
    objective: 'Tìm vật liệu giúp đệ tử yếu ổn định khí tức.',
    requirement: 'Đã học về Ngũ Hành sơ vấn.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 4, description: 'Hái 4 Linh Thảo có mộc khí ôn hoà.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Đưa dược liệu cho Mộc Thanh Y luyện đan an thần.' },
    ],
    rewards: { linhThach: 140, exp: 300, congHien: 25, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }] },
    loreSummary: 'Reinforces the bible theme that weak roots can still walk the Dao.',
  }),
  sideQuest({
    key: 'phase21_side_007',
    name: 'Gió Lạnh Hắc Lâm',
    description:
      'Hắc Lâm có tiếng khóc trẻ con lẫn trong gió; đó không phải ma quỷ, mà là bùa truyền âm của người hái thuốc mất tích.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_side_ling_root',
    prerequisiteQuestKey: 'phase21_ch02_main_02',
    objective: 'Tìm người hái thuốc trước khi Hắc Lâm nuốt dấu vết.',
    requirement: 'Đã khảo sát Hắc Lâm ven Linh Tuyền.',
    steps: [
      { id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Lần theo tiếng bùa truyền âm trong Hắc Lâm.' },
      { id: 'step_02', kind: 'kill', targetType: 'monster', targetId: 'thi_quy', count: 2, description: 'Đánh lui 2 Thi Quỷ chặn đường thoát.' },
    ],
    rewards: { linhThach: 160, exp: 360, items: [{ itemKey: 'hoi_nguyen_dan', qty: 1 }] },
    loreSummary: 'A rescue story that makes Hắc Lâm dangerous without random slaughter.',
  }),
  sideQuest({
    key: 'phase21_side_008',
    name: 'Bình Nước Luyện Khí',
    description:
      'Một bình nước Linh Tuyền bị đổi thành nước thường; chuyện nhỏ này có thể khiến tân đệ tử tẩu hoả.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_side_ling_spring',
    prerequisiteQuestKey: 'phase21_ch02_main_02',
    objective: 'Tìm nguồn nước bị tráo và người làm rối mạch tu luyện.',
    requirement: 'Đã mở mạch Linh Tuyền.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 1, description: 'Dùng Hàn Ngọc thử độ thuần của nước.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_report_water_swap', count: 1, description: 'Chọn báo công khai hay âm thầm cảnh cáo kẻ đổi nước.' },
    ],
    rewards: { linhThach: 170, exp: 390, congHien: 35, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'Low-stakes sect intrigue tied to cultivation safety.',
  }),
  sideQuest({
    key: 'phase21_side_009',
    name: 'Lá Đen Không Rụng',
    description:
      'Lá Hắc Lâm chuyển đen nhưng không rụng, giữ trong gân lá một thứ khí lạnh giống Tịch Linh.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_side_ling_spring',
    prerequisiteQuestKey: 'phase21_ch02_main_03',
    objective: 'Thu mẫu lá đen để phân biệt độc Mộc và Tịch Linh.',
    requirement: 'Đã đánh lui yêu vật ăn rễ.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'hac_yeu_xa', count: 2, description: 'Đánh lui 2 Hắc Yêu Xà quanh cây lá đen.' },
      { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 3, description: 'Thu 3 mẫu linh thảo nhiễm sắc đen.' },
    ],
    rewards: { linhThach: 180, exp: 420, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'Adds diagnostic nuance to Tịch Linh corruption.',
  }),
  sideQuest({
    key: 'phase21_side_010',
    name: 'Một Viên Đan Không Bán',
    description:
      'Thương nhân muốn mua đan hộ tâm với giá cao; Mộc Thanh Y bắt người chơi chọn giữa lợi nhỏ và mạng đệ tử.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_side_ling_root',
    prerequisiteQuestKey: 'phase21_ch02_main_04',
    objective: 'Giữ đan hộ tâm cho người thật sự cần.',
    requirement: 'Đã chuẩn bị kỹ pháp hộ tâm.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Chuẩn bị 1 Linh Lộ Đan hộ tâm.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_refuse_pill_buyer', count: 1, description: 'Chọn bán lấy tiền hay giữ đan cứu đồng môn.' },
    ],
    rewards: { linhThach: 150, exp: 430, congHien: 45, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'Moral economy beat: rewards contribution, not profiteering.',
  }),
  sideQuest({
    key: 'phase21_side_011',
    name: 'Thư Kiếm Không Gửi',
    description:
      'Hàn Dạ mang theo thư thách đấu nhưng chưa gửi, vì người hắn muốn đấu đã chết dưới một vết kiếm giả.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_han_da_rival',
    prerequisiteQuestKey: 'phase21_ch03_main_03',
    objective: 'Giúp Hàn Dạ kiểm chứng vết kiếm trước khi hắn khiêu chiến nhầm người.',
    requirement: 'Đã gặp Hàn Dạ.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 2, description: 'Thu 2 mảnh kiếm khí còn bám trên Tinh Thiết.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Đưa mảnh kiếm cho Hàn Dạ phân tích.' },
    ],
    rewards: { linhThach: 220, exp: 520, affinity: [{ npcKey: 'npc_han_da', delta: 4 }] },
    loreSummary: 'Humanizes Hàn Dạ’s pride as grief and duty.',
  }),
  sideQuest({
    key: 'phase21_side_012',
    name: 'Tiếng Chuông Hộ Sơn',
    description:
      'Chuông hộ sơn đã câm nhiều năm; sửa chuông không giúp trận mạnh hơn ngay, nhưng giúp người trong núi biết khi nào cần chạy.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_sect_rebuild',
    prerequisiteQuestKey: 'phase21_ch03_main_01',
    objective: 'Sửa chuông cảnh báo ở mốc trận cũ.',
    requirement: 'Đã bắt đầu sửa hộ sơn trận.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 4, description: 'Chuẩn bị 4 Tinh Thiết để vá thân chuông.' },
      { id: 'step_02', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Treo lại chuông ở mép Sơn Cốc.' },
    ],
    rewards: { linhThach: 230, exp: 540, congHien: 70, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'Sect infrastructure side story with practical stakes.',
  }),
  sideQuest({
    key: 'phase21_side_013',
    name: 'Đá Quan Giữ Mốc',
    description:
      'Đá Quan Yêu Tinh không tấn công người trước; chúng đang canh một mốc trận bị dùng làm mộ tạm.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_sect_rebuild',
    prerequisiteQuestKey: 'phase21_ch03_main_02',
    objective: 'Dời mộ tạm khỏi mốc trận mà không phá oán khí.',
    requirement: 'Đã cắm đinh trận Sơn Cốc.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'da_quan', count: 2, description: 'Đánh lui 2 Đá Quan Yêu Tinh canh mộ.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_move_grave_or_array', count: 1, description: 'Chọn dời mộ trước hay nối trận trước.' },
    ],
    rewards: { linhThach: 240, exp: 560, congHien: 75, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'Adds respect-for-dead nuance to sect rebuilding.',
  }),
  sideQuest({
    key: 'phase21_side_014',
    name: 'Bạn Hay Đối Thủ',
    description:
      'Hàn Dạ không quen nói cảm ơn; hắn đặt một buổi tỷ kiếm nhỏ để quyết định cách gọi người chơi.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_han_da_rival',
    prerequisiteQuestKey: 'phase21_ch03_main_05',
    objective: 'Hoàn thành tỷ kiếm danh dự với Hàn Dạ.',
    requirement: 'Đã đồng hành lần đầu với Hàn Dạ.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'huyet_lang', count: 2, description: 'Dọn 2 Huyết Lang khỏi sân tỷ kiếm tạm.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_han_da_friend_or_rival', count: 1, description: 'Chọn gọi Hàn Dạ là bạn, đối thủ hoặc kiếm khách đáng tin.' },
    ],
    rewards: { linhThach: 260, exp: 620, affinity: [{ npcKey: 'npc_han_da', delta: 6 }] },
    loreSummary: 'Relationship-defining side quest linked to the party tutorial.',
  }),
  sideQuest({
    key: 'phase21_side_015',
    name: 'Gạch Nứt Tàng Kinh',
    description:
      'Tàng Kinh Các cũ nứt nền, để lộ vài chữ về Hoa Thiên Sơn mà không ai trong tông môn còn nhớ rõ.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_sect_memory',
    prerequisiteQuestKey: 'phase21_ch03_main_04',
    objective: 'Chép lại chữ cổ trước khi nền đá sụp.',
    requirement: 'Đã điều tra vết kiếm trong trận.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 2, description: 'Dùng 2 Phù Vân Ngọc in lại chữ cổ.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Đưa bản in chữ cổ cho Lăng Vân Sinh.' },
    ],
    rewards: { linhThach: 250, exp: 600, congHien: 90, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }] },
    loreSummary: 'Foreshadows Hoa Thiên Sơn through damaged archives.',
  }),
  sideQuest({
    key: 'phase21_side_016',
    name: 'Dây Mộc Che Miệng Giếng',
    description:
      'Tô Nguyệt Ly không phá dây mộc quanh giếng vì mỗi dây buộc một lời thề của nhánh lưu đày.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_old_well',
    prerequisiteQuestKey: 'phase21_ch04_main_01',
    objective: 'Gỡ dây mộc đúng thứ tự để không phá lời thề cổ.',
    requirement: 'Đã gặp người giữ giếng cũ.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 5, description: 'Tìm 5 nhánh Linh Thảo cùng mạch để thay dây thề.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_untie_oath_vines', count: 1, description: 'Chọn gỡ dây theo thứ tự sinh hay khắc của Ngũ Hành.' },
    ],
    rewards: { linhThach: 320, exp: 850, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }] },
    loreSummary: 'Connects old-well mechanics to exile vows.',
  }),
  sideQuest({
    key: 'phase21_side_017',
    name: 'Gia Phả Bị Xoá',
    description:
      'Một trang gia phả chỉ còn họ Tô và một vệt máu; Tô Nguyệt Ly muốn biết ai đã xoá tên người thân.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_old_well',
    prerequisiteQuestKey: 'phase21_ch04_main_02',
    objective: 'Khôi phục mảnh gia phả của nhánh Hoa Thiên lưu đày.',
    requirement: 'Đã khôi phục chìa đá Ngũ Hành.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'thien_linh_ngoc', count: 1, description: 'Dùng Thiên Linh Ngọc soi chữ bị xoá.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Cùng Tô Nguyệt Ly đọc phần tên còn lại.' },
    ],
    rewards: { linhThach: 350, exp: 900, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 6 }] },
    loreSummary: 'Personalizes the erased Hoa Thiên branch through family records.',
  }),
  sideQuest({
    key: 'phase21_side_018',
    name: 'Mắt Trăng Trong Nước',
    description:
      'Dưới giếng hiện một mặt trăng thứ hai; nó phản chiếu người đứng cạnh hơn là người nhìn xuống.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_blood_moon_realm',
    prerequisiteQuestKey: 'phase21_ch04_main_03',
    objective: 'Giải phản chiếu Huyết Nguyệt để tìm đường an toàn.',
    requirement: 'Đã mở cổng Huyết Nguyệt.',
    steps: [
      { id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Quan sát phản chiếu ở cửa giếng.' },
      { id: 'step_02', kind: 'kill', targetType: 'monster', targetId: 'tang_diep_yeu_phu', count: 3, description: 'Đánh tan 3 yêu phụ do bóng trăng gọi ra.' },
    ],
    rewards: { linhThach: 380, exp: 980, items: [{ itemKey: 'co_thien_dan', qty: 1 }] },
    loreSummary: 'Makes Blood Moon navigation a character-reflection puzzle.',
  }),
  sideQuest({
    key: 'phase21_side_019',
    name: 'Tàn Hồn Không Muốn Quên',
    description:
      'Một tàn hồn nhỏ trong bí cảnh không cần siêu độ; nó chỉ xin ai đó nhớ tên người cuối cùng đóng cổng.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_blood_moon_realm',
    prerequisiteQuestKey: 'phase21_ch04_main_04',
    objective: 'Ghi nhớ tên tàn hồn Hoa Thiên và đem về tông môn.',
    requirement: 'Đã gặp tàn hồn Hoa Thiên.',
    steps: [
      { id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_remember_remnant_name', count: 1, description: 'Chọn khắc tên lên ngọc hay ghi vào tâm quyết.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Báo tên tàn hồn cho Lăng Vân Sinh.' },
    ],
    rewards: { linhThach: 360, exp: 1_000, congHien: 100, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }] },
    loreSummary: 'Lore reward centered on remembrance rather than currency.',
  }),
  sideQuest({
    key: 'phase21_side_020',
    name: 'Mộc Ấn Trên Tay Áo',
    description:
      'Tay áo Tô Nguyệt Ly có một mộc ấn không thuộc Hoa Thiên hiện tại; Mộc Thanh Y nhận ra cách thêu đã thất truyền.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_old_well',
    prerequisiteQuestKey: 'phase21_ch04_main_05',
    objective: 'Đối chiếu mộc ấn lưu đày với dược văn Hoa Thiên.',
    requirement: 'Đã mang chứng vật Huyết Nguyệt về tông môn.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 6, description: 'Chuẩn bị 6 Linh Thảo để hiện dược văn cũ.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Nhờ Mộc Thanh Y đọc mộc ấn thất truyền.' },
    ],
    rewards: { linhThach: 390, exp: 1_050, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }] },
    loreSummary: 'Links Tô Nguyệt Ly’s exile branch to Mộc Thanh Y’s alchemy lineage.',
  }),
  sideQuest({
    key: 'phase21_side_021',
    name: 'Người Sống Sót Không Nói',
    description:
      'Người sống sót sau thảm án chỉ viết một chữ “trắng”; Hàn Dạ sợ đó là màu áo của chính đạo.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_bloodstone_case',
    prerequisiteQuestKey: 'phase21_ch05_main_01',
    objective: 'Bảo vệ người sống sót để lấy lời khai không bị Tịch Linh cắt.',
    requirement: 'Đã điều tra thôn dưới thềm đá.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'huyet_lang', count: 3, description: 'Đánh lui 3 Huyết Lang lần theo máu người sống sót.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_survivor_white_clue', count: 1, description: 'Chọn giấu manh mối chữ trắng hay báo cho chính đạo.' },
    ],
    rewards: { linhThach: 460, exp: 1_350, affinity: [{ npcKey: 'npc_han_da', delta: 4 }] },
    loreSummary: 'Deepens the massacre clue without blaming one faction too early.',
  }),
  sideQuest({
    key: 'phase21_side_022',
    name: 'Máu Không Đông',
    description:
      'Máu ở thềm đá không đông vì có linh thức bị giữ lại; Huyết La Sát nói đó không phải thủ pháp giết người của nàng.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_huyet_la_sat_mercy',
    prerequisiteQuestKey: 'phase21_ch05_main_03',
    objective: 'Thu mẫu huyết khí để kiểm chứng lời Huyết La Sát.',
    requirement: 'Đã đối chất Huyết La Sát.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'huyet_tinh', count: 3, description: 'Thu 3 Huyết Tinh không đông.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Đưa mẫu cho Huyết La Sát phân biệt huyết thuật.' },
    ],
    rewards: { linhThach: 500, exp: 1_500, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }] },
    loreSummary: 'Lets Huyết La Sát demonstrate expertise without absolving her past.',
  }),
  sideQuest({
    key: 'phase21_side_023',
    name: 'Một Nấm Mộ Không Tên',
    description:
      'Huyết La Sát lén chôn một đứa trẻ trong thôn; nàng không giải thích, chỉ đặt kiếm quay lưng về phía chính đạo.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_huyet_la_sat_mercy',
    prerequisiteQuestKey: 'phase21_ch05_main_04',
    objective: 'Bảo vệ nghi thức chôn cất khỏi yêu thú hút huyết khí.',
    requirement: 'Đã xem phản chiếu huyết thạch.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'huyet_anh', count: 3, description: 'Đánh tan 3 Huyết Ảnh kéo tới nấm mộ.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_unnamed_grave', count: 1, description: 'Chọn hỏi tên đứa trẻ hay giữ im lặng.' },
    ],
    rewards: { linhThach: 520, exp: 1_600, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 6 }] },
    loreSummary: 'Adds tenderness to Huyết La Sát without erasing her brutality.',
  }),
  sideQuest({
    key: 'phase21_side_024',
    name: 'Kiếm Sạch Không Sạch',
    description:
      'Hàn Dạ lau kiếm mãi không sạch mùi máu thôn; vấn đề không nằm trên kiếm mà trong cách hắn nhìn công lý.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_bloodstone_case',
    prerequisiteQuestKey: 'phase21_ch05_main_05',
    objective: 'Giúp Hàn Dạ định lại lời thề kiếm sau phán quyết Huyết La Sát.',
    requirement: 'Đã chọn tha, giết hoặc hợp tác với Huyết La Sát.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 2, description: 'Dùng 2 Hàn Ngọc tẩy sát khí bám kiếm.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_han_da_justice_oath', count: 1, description: 'Chọn lời thề kiếm: trảm tà, hộ người, hay tìm sự thật.' },
    ],
    rewards: { linhThach: 540, exp: 1_650, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'Moves Hàn Dạ from judgment toward truth-seeking.',
  }),
  sideQuest({
    key: 'phase21_side_025',
    name: 'Chén Rượu Ma Đạo',
    description:
      'Huyết La Sát mời một chén rượu đỏ để hỏi người chơi sợ ma đạo, sợ nàng, hay sợ giống nàng.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_huyet_la_sat_mercy',
    prerequisiteQuestKey: 'phase21_ch05_main_05',
    objective: 'Trả lời Huyết La Sát về ranh giới chính-ma.',
    requirement: 'Đã hoàn thành chương Ma Tu Xuất Thế.',
    steps: [
      { id: 'step_01', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_demonic_wine_answer', count: 1, description: 'Chọn uống, từ chối, hoặc đổ rượu tế người chết.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Nghe Huyết La Sát kể một mảnh quá khứ Hoa Thiên.' },
    ],
    rewards: { linhThach: 480, exp: 1_700, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 7 }] },
    loreSummary: 'Relationship and ideology quest with low material reward.',
  }),
  sideQuest({
    key: 'phase21_side_026',
    name: 'Kim Sa Không Vàng',
    description:
      'Tiên Kim Sa trên tế đàn ngả xám, báo rằng Kim hệ đang bị thứ gì đó ăn mất sắc bén.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_01',
    objective: 'Thanh lọc Tiên Kim Sa trước khi tế đàn phản phệ.',
    requirement: 'Đã bắt đầu Ngũ Hành cộng minh.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'tien_kim_sa', count: 2, description: 'Thu 2 Tiên Kim Sa còn giữ kim quang.' },
      { id: 'step_02', kind: 'kill', targetType: 'monster', targetId: 'kim_quang_thach_giap', count: 2, description: 'Đánh lui 2 Kim Quang Thạch Giáp bị hút tới.' },
    ],
    rewards: { linhThach: 560, exp: 1_850, congHien: 120, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }] },
    loreSummary: 'Elemental side story for the Metal anchor.',
  }),
  sideQuest({
    key: 'phase21_side_027',
    name: 'Mộc Khí Của Đại Sư Tỷ',
    description:
      'Mộc Thanh Y cười như không sao, nhưng mộc khí của nàng lệch một nhịp khi tế đàn gọi tới Tịch Linh.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_02',
    objective: 'Ổn định Mộc khí của Mộc Thanh Y trong lúc tế đàn vận hành.',
    requirement: 'Đã dựng năm dấu ấn một trận.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'van_linh_dan', count: 1, description: 'Chuẩn bị 1 Vạn Linh Đan trợ mạch.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'Thuyết phục Mộc Thanh Y nghỉ một hơi trước khi tiếp tục.' },
    ],
    rewards: { linhThach: 540, exp: 1_820, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 6 }] },
    loreSummary: 'Connects Five Elements to Mộc Thanh Y’s hidden corrosion.',
  }),
  sideQuest({
    key: 'phase21_side_028',
    name: 'Thuỷ Ảnh Không Người',
    description:
      'Hàn Ngọc trên tế đàn phản chiếu đủ mọi người trừ người chơi, như thể Hạt Giống Vô Danh không có bóng.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_02',
    objective: 'Giải phản chiếu Thuỷ hệ bị thiếu bóng.',
    requirement: 'Đã cân bằng năm dấu ấn.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 2, description: 'Đặt 2 Hàn Ngọc quanh điểm Thuỷ hệ.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_water_shadow_seed', count: 1, description: 'Chọn nhìn vào bóng người khác hay nhìn thẳng vào khoảng trống.' },
    ],
    rewards: { linhThach: 560, exp: 1_900, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }] },
    loreSummary: 'Foreshadows the Nameless Seed as outside normal fate reflections.',
  }),
  sideQuest({
    key: 'phase21_side_029',
    name: 'Lửa Không Đốt Người',
    description:
      'Hoả điểm của tế đàn bùng lên nhưng không nóng; Huyết La Sát bảo đó là lửa từng dùng để thẩm vấn linh hồn.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_03',
    objective: 'Dập Hoả điểm giả trước khi nó gọi ký ức huyết ngục.',
    requirement: 'Đã phân vai đồng đội trên tế đàn.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'huyet_anh', count: 2, description: 'Đánh tan 2 Huyết Ảnh do hoả điểm gọi ra.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_false_fire_memory', count: 1, description: 'Chọn dập lửa bằng huyết khí hay bằng trận Hoa Thiên.' },
    ],
    rewards: { linhThach: 570, exp: 1_950, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }] },
    loreSummary: 'Elemental Fire beat filtered through Huyết La Sát’s past.',
  }),
  sideQuest({
    key: 'phase21_side_030',
    name: 'Thổ Ấn Dưới Chân',
    description:
      'Thổ điểm không nằm trên tế đàn mà dưới chân mọi người; Lăng Vân Sinh nói nền tông môn cũng là một lời thề.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_03',
    objective: 'Ổn định Thổ ấn để tế đàn không sụp vào mạch cũ.',
    requirement: 'Đã thiết lập phối hợp đồng đạo.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'da_quan', count: 3, description: 'Đánh lui 3 Đá Quan Yêu Tinh trồi lên từ nền trận.' },
      { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 3, description: 'Đóng 3 Tinh Thiết giữ Thổ ấn.' },
    ],
    rewards: { linhThach: 590, exp: 2_000, congHien: 140, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }] },
    loreSummary: 'Elemental Earth beat tied to the physical sect foundation.',
  }),
  sideQuest({
    key: 'phase21_side_031',
    name: 'Món Nợ Với Huyền Kiếm',
    description:
      'Hoa Thiên từng mượn Huyền Kiếm một hộp kiếm phù nhưng chưa trả; Hàn Dạ giả vờ không quan tâm, nhưng vẫn giữ giấy nợ.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_han_da_rival',
    prerequisiteQuestKey: 'phase21_ch03_main_05',
    objective: 'Trả món nợ nhỏ để giữ danh dự giữa hai tông.',
    requirement: 'Đã mở quan hệ đồng hành với Hàn Dạ.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 2, description: 'Chuẩn bị 2 Phù Vân Ngọc làm kiếm phù thay thế.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Trả kiếm phù cho Hàn Dạ.' },
    ],
    rewards: { linhThach: 300, exp: 760, congHien: 60, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'Sect diplomacy side quest connecting Hoa Thiên and Huyền Kiếm.',
  }),
  sideQuest({
    key: 'phase21_side_032',
    name: 'Chợ Nhỏ Dưới Núi',
    description:
      'Chợ dưới núi sợ mua đồ Hoa Thiên vì tin đồn ma khí; Lăng Vân Sinh muốn giải thích bằng việc làm, không bằng lời.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_sect_rebuild',
    prerequisiteQuestKey: 'phase21_ch03_main_01',
    objective: 'Đưa hàng an toàn xuống chợ để xóa tin đồn ma khí.',
    requirement: 'Đã bắt đầu xây lại uy tín tông môn.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 6, description: 'Chuẩn bị 6 Linh Thảo sạch khí.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_market_reputation', count: 1, description: 'Chọn bán rẻ lấy lòng dân hay tặng cho y quán.' },
    ],
    rewards: { linhThach: 260, exp: 620, congHien: 85, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'Market-side reputation hook without adding trading/gifting systems.',
  }),
  sideQuest({
    key: 'phase21_side_033',
    name: 'Bài Thuốc Cho Kiếm Thương',
    description:
      'Hàn Dạ bị kiếm thương nhưng không chịu nhận thuốc Hoa Thiên; Mộc Thanh Y nhờ người chơi đưa thuốc theo cách hắn không từ chối được.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_side_han_da_rival',
    prerequisiteQuestKey: 'phase21_ch03_main_05',
    objective: 'Chữa kiếm thương cho Hàn Dạ mà giữ thể diện của hắn.',
    requirement: 'Đã cùng Hàn Dạ chiến đấu.',
    endNpcKey: 'npc_han_da',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Chuẩn bị 1 Hồi Nguyên Đan.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_han_da', count: 1, description: 'Đưa thuốc cho Hàn Dạ dưới danh nghĩa trao đổi kiếm ý.' },
    ],
    rewards: { linhThach: 310, exp: 820, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'Cross-NPC care quest between Mộc Thanh Y and Hàn Dạ.',
  }),
  sideQuest({
    key: 'phase21_side_034',
    name: 'Một Mẩu Xương Rồng',
    description:
      'Trong Huyết Nguyệt có mẩu xương nhỏ mang long khí; Tô Nguyệt Ly không muốn giao nó cho ai chưa hiểu giá của truyền thừa.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_side_blood_moon_realm',
    prerequisiteQuestKey: 'phase21_ch04_main_05',
    objective: 'Niêm phong mẩu xương long khí khỏi người săn bảo.',
    requirement: 'Đã rời bí cảnh Huyết Nguyệt.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'kim_quang_thach_giap', count: 2, description: 'Đánh lui 2 Thạch Giáp bị long khí thu hút.' },
      { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thien_linh_ngoc', count: 1, description: 'Dùng Thiên Linh Ngọc niêm phong long khí.' },
    ],
    rewards: { linhThach: 420, exp: 1_120, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }] },
    loreSummary: 'Subtle dragon-bone lore bridge to boss binding.',
  }),
  sideQuest({
    key: 'phase21_side_035',
    name: 'Tin Đồn Về La Sát',
    description:
      'Ngoại môn đồn Huyết La Sát ăn tim người; nàng nghe thấy nhưng chỉ cười, còn Mộc Thanh Y thì không.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_side_huyet_la_sat_mercy',
    prerequisiteQuestKey: 'phase21_ch05_main_05',
    objective: 'Dập tin đồn đủ để đệ tử không tự chuốc hoạ.',
    requirement: 'Đã đưa ra phán quyết với Huyết La Sát.',
    endNpcKey: 'npc_huyet_la_sat',
    steps: [
      { id: 'step_01', kind: 'talk', targetType: 'npc', targetId: 'npc_huyet_la_sat', count: 1, description: 'Hỏi Huyết La Sát muốn xử lý tin đồn thế nào.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_lasat_rumor_response', count: 1, description: 'Chọn phản bác, im lặng hay biến tin đồn thành cảnh báo.' },
    ],
    rewards: { linhThach: 500, exp: 1_500, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 4 }] },
    loreSummary: 'A social side quest after the moral branch.',
  }),
  sideQuest({
    key: 'phase21_side_036',
    name: 'Bản Đồ Năm Điểm',
    description:
      'Tô Nguyệt Ly ghép bản đồ cũ với tế đàn Ngũ Hành và phát hiện năm điểm không trùng địa mạch hiện tại.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_01',
    objective: 'Ghép bản đồ cổ để định vị năm điểm tế đàn.',
    requirement: 'Đã khởi động cộng minh Ngũ Hành.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 3, description: 'Dùng 3 Phù Vân Ngọc giữ nét bản đồ cũ.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_to_nguyet_ly', count: 1, description: 'Cùng Tô Nguyệt Ly ghép bản đồ năm điểm.' },
    ],
    rewards: { linhThach: 560, exp: 1_850, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }] },
    loreSummary: 'Map-lore support for the Five Element ritual.',
  }),
  sideQuest({
    key: 'phase21_side_037',
    name: 'Kiếm Trận Giữ Phía Tây',
    description:
      'Hàn Dạ giữ phía Tây tế đàn nhưng kiếm trận của hắn thiếu một người tin tưởng đứng sau lưng.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_03',
    objective: 'Ổn định kiếm trận phía Tây cùng Hàn Dạ.',
    requirement: 'Đã phân vai đồng đội trên tế đàn.',
    steps: [
      { id: 'step_01', kind: 'kill', targetType: 'monster', targetId: 'kim_dieu_thuong_phong', count: 1, description: 'Đánh lui Kim Điêu Thượng Phong thử kiếm trận.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_stand_behind_han_da', count: 1, description: 'Chọn đứng sau lưng Hàn Dạ hay sóng vai với hắn.' },
    ],
    rewards: { linhThach: 620, exp: 2_050, affinity: [{ npcKey: 'npc_han_da', delta: 6 }] },
    loreSummary: 'Party trust side quest for Hàn Dạ at the ritual climax.',
  }),
  sideQuest({
    key: 'phase21_side_038',
    name: 'Đan Hương Sau Tế Đàn',
    description:
      'Sau mỗi lần tế đàn rung, mùi đan của Mộc Thanh Y đổi khác; nàng nhờ người chơi ngửi giúp vì chính nàng không còn phân biệt được.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_04',
    objective: 'Kiểm tra đan hương để phát hiện Tịch Linh ăn mòn.',
    requirement: 'Đã ổn định Kim Phách Long Điêu.',
    steps: [
      { id: 'step_01', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Chuẩn bị 1 Thanh Lam Đan làm mẫu thanh tâm.' },
      { id: 'step_02', kind: 'talk', targetType: 'npc', targetId: 'npc_moc_thanh_y', count: 1, description: 'So đan hương cùng Mộc Thanh Y.' },
    ],
    rewards: { linhThach: 600, exp: 2_000, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 6 }] },
    loreSummary: 'Foreshadows Mộc Thanh Y’s later crisis after Phase 21.',
  }),
  sideQuest({
    key: 'phase21_side_039',
    name: 'Một Câu Hỏi Cho Chưởng Môn',
    description:
      'Sau khi Tịch Thiên được nhắc tên, Lăng Vân Sinh không ngủ. Người chơi có thể hỏi một điều, nhưng câu trả lời sẽ đổi cách nhìn Hoa Thiên.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_sect_memory',
    prerequisiteQuestKey: 'phase21_ch06_main_05',
    objective: 'Hỏi Lăng Vân Sinh một bí mật về Hoa Thiên và Tịch Thiên.',
    requirement: 'Đã hoàn thành Thiên Mệnh Chưa Thành.',
    steps: [
      { id: 'step_01', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Gặp Lăng Vân Sinh trong điện vắng.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_question_sect_master', count: 1, description: 'Chọn hỏi về Tịch Thiên, Hoa Thiên Sơn hoặc Hạt Giống Vô Danh.' },
    ],
    rewards: { linhThach: 650, exp: 2_100, congHien: 160, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 7 }] },
    loreSummary: 'Post-chapter lore quest that opens future arcs without spoiling final twist.',
  }),
  sideQuest({
    key: 'phase21_side_040',
    name: 'Năm Người Một Lời Thề',
    description:
      'Lăng Vân Sinh, Mộc Thanh Y, Hàn Dạ, Tô Nguyệt Ly và Huyết La Sát đứng quanh tế đàn; không ai hoàn toàn tin ai, nhưng cùng thề không để Tịch Thiên lấy Hạt Giống.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_side_five_element_rite',
    prerequisiteQuestKey: 'phase21_ch06_main_05',
    objective: 'Chứng kiến lời thề đồng minh tạm thời sau Phase 21.',
    requirement: 'Đã khép lại chuỗi chính Ngũ Hành Thiên Mệnh.',
    steps: [
      { id: 'step_01', kind: 'talk', targetType: 'npc', targetId: 'npc_lang_van_sinh', count: 1, description: 'Tập hợp mọi người quanh tế đàn.' },
      { id: 'step_02', kind: 'choice', targetType: 'choice', targetId: 'choice_phase21_five_person_oath', count: 1, description: 'Chọn lời thề: bảo vệ người, bảo vệ tông môn, hoặc bảo vệ tự do chọn đạo.' },
    ],
    rewards: {
      linhThach: 700,
      exp: 2_200,
      congHien: 180,
      affinity: [
        { npcKey: 'npc_lang_van_sinh', delta: 4 },
        { npcKey: 'npc_moc_thanh_y', delta: 4 },
        { npcKey: 'npc_han_da', delta: 4 },
        { npcKey: 'npc_to_nguyet_ly', delta: 4 },
        { npcKey: 'npc_huyet_la_sat', delta: 4 },
      ],
    },
    loreSummary: 'A capstone side quest that binds the five existing core NPCs into one uneasy alliance.',
  }),
] as const;
