import type { QuestDef, QuestRewardDef, QuestStepDef } from './quests';

type ChapterKey =
  | 'chapter_pham_nhan_nhap_dao'
  | 'chapter_linh_can_thuc_tinh'
  | 'chapter_tong_mon_so_khoi'
  | 'chapter_bi_canh_huyet_nguyet'
  | 'chapter_ma_tu_xuat_the'
  | 'chapter_ngu_hanh_thien_menh';

interface Phase21MainQuestInput {
  key: string;
  name: string;
  description: string;
  realmKey: string;
  requiredRealmOrder: number;
  giverNpcKey: string;
  chapterKey: ChapterKey;
  chainKey: string;
  prerequisiteQuestKey: string | null;
  previousQuestKey: string | null;
  nextQuestKey: string | null;
  objective: string;
  requirement: string;
  startNpcKey: string;
  endNpcKey: string;
  dialogueKeys: readonly string[];
  steps: readonly QuestStepDef[];
  rewards: QuestRewardDef;
  loreSummary: string;
}

function mainQuest(input: Phase21MainQuestInput): QuestDef {
  return {
    ...input,
    kind: 'main',
    order: Number(input.key.match(/_(\d{2})$/)?.[1] ?? '0'),
  };
}

export const PHASE21_MAIN_QUESTS: readonly QuestDef[] = [
  mainQuest({
    key: 'phase21_ch01_main_01',
    name: 'Bậc Thềm Hoa Thiên',
    description:
      'Lăng Vân Sinh mở cửa Hoa Thiên Môn cho một phàm nhân bị chê căn cơ yếu.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_chapter_01_main',
    prerequisiteQuestKey: 'phamnhan_main_01',
    previousQuestKey: null,
    nextQuestKey: 'phase21_ch01_main_02',
    objective: 'Ra mắt chưởng môn và nhận khảo nghiệm nhập môn.',
    requirement: 'Đã hoàn thành Hoa Thiên Tuyển Đồ.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: [
      'story_dlg_lang_van_sinh_chapter_1_intro',
      'story_dlg_lang_van_sinh_friendly_chat',
    ],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Nghe Lăng Vân Sinh giải thích quy củ Hoa Thiên Môn.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_accept_outer_disciple_oath',
        count: 1,
        description: 'Lập lời thề ngoại môn: tu tâm trước, tu lực sau.',
      },
    ],
    rewards: {
      linhThach: 90,
      exp: 160,
      congHien: 15,
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }],
    },
    loreSummary:
      'Expands the story-bible onboarding beat where Hoa Thiên Môn accepts weak disciples because dao heart matters.',
  }),
  mainQuest({
    key: 'phase21_ch01_main_02',
    name: 'Đại Sư Tỷ Giao Việc',
    description:
      'Mộc Thanh Y không cho đệ tử mới nhàn rỗi: việc vặt đầu tiên là thử đạo tâm.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_chapter_01_main',
    prerequisiteQuestKey: 'phase21_ch01_main_01',
    previousQuestKey: 'phase21_ch01_main_01',
    nextQuestKey: 'phase21_ch01_main_03',
    objective: 'Hoàn thành việc ngoại môn đầu tiên cho Mộc Thanh Y.',
    requirement: 'Đã nhận thân phận ngoại môn.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'linh_thao',
        count: 3,
        description: 'Thu 3 Linh Thảo còn sót lại sau hậu sơn.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_moc_thanh_y',
        count: 1,
        description: 'Báo với Mộc Thanh Y rằng linh điền có dấu héo lạ.',
      },
    ],
    rewards: {
      linhThach: 80,
      exp: 180,
      congHien: 20,
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }],
    },
    loreSummary:
      'Foreshadows Mộc Thanh Y’s Tịch Linh Chủng arc through withered spiritual fields.',
  }),
  mainQuest({
    key: 'phase21_ch01_main_03',
    name: 'Sơn Cốc Đêm Đầu',
    description:
      'Tiếng yêu thú quanh Thanh Khê buộc đệ tử mới rời sân tông môn trong đêm đầu tiên.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_chapter_01_main',
    prerequisiteQuestKey: 'phase21_ch01_main_02',
    previousQuestKey: 'phase21_ch01_main_02',
    nextQuestKey: 'phase21_ch01_main_04',
    objective: 'Dọn yêu thú nhỏ quanh Sơn Cốc để bảo vệ linh điền.',
    requirement: 'Đã phát hiện linh điền héo lạ.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'son_coc',
        count: 1,
        description: 'Tuần tra Sơn Cốc gần Thanh Khê.',
      },
      {
        id: 'step_02',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'son_thu_lon',
        count: 4,
        description: 'Đánh bại 4 Sơn Thử Lớn phá linh điền.',
      },
    ],
    rewards: {
      linhThach: 120,
      exp: 220,
      items: [{ itemKey: 'linh_lo_dan', qty: 1 }],
    },
    loreSummary:
      'Grounds the first combat in Thanh Khê protection instead of a disconnected kill quota.',
  }),
  mainQuest({
    key: 'phase21_ch01_main_04',
    name: 'Dấu Khí Sau Rễ Cỏ',
    description:
      'Dưới rễ linh thảo còn sót lại một sợi khí xám lạnh không thuộc yêu thú thường.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_chapter_01_main',
    prerequisiteQuestKey: 'phase21_ch01_main_03',
    previousQuestKey: 'phase21_ch01_main_03',
    nextQuestKey: 'phase21_ch01_main_05',
    objective: 'Thu mẫu khí lạ và báo cáo cho Lăng Vân Sinh.',
    requirement: 'Đã dọn yêu thú quanh Sơn Cốc.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'phu_van_ngoc',
        count: 1,
        description: 'Dùng Phù Vân Ngọc niêm phong sợi khí xám.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Đưa mẫu khí cho Lăng Vân Sinh xem xét.',
      },
    ],
    rewards: {
      linhThach: 140,
      exp: 260,
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }],
    },
    loreSummary:
      'Turns the first Tịch Linh hint into a concrete report before the Nameless Seed beat.',
  }),
  mainQuest({
    key: 'phase21_ch01_main_05',
    name: 'Mầm Không Tên',
    description:
      'Hạt Giống Vô Danh rung lên khi sợi khí xám chạm phong ấn cũ trong hậu sơn.',
    realmKey: 'phamnhan',
    requiredRealmOrder: 0,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_chapter_01_main',
    prerequisiteQuestKey: 'phase21_ch01_main_04',
    previousQuestKey: 'phase21_ch01_main_04',
    nextQuestKey: 'phase21_ch02_main_01',
    objective: 'Chứng kiến Hạt Giống Vô Danh cộng hưởng và khép lại nhập môn.',
    requirement: 'Đã thu mẫu khí lạ.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'son_coc',
        count: 1,
        description: 'Theo Lăng Vân Sinh tới phong ấn hậu sơn.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_seed_resonance',
        count: 1,
        description: 'Chọn cách chạm vào Hạt Giống Vô Danh: cẩn trọng hoặc quả quyết.',
      },
    ],
    rewards: {
      linhThach: 180,
      exp: 320,
      congHien: 30,
      items: [{ itemKey: 'so_kiem', qty: 1 }],
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }],
    },
    loreSummary:
      'Completes chapter 1 and explicitly links the Nameless Seed to Hoa Thiên inheritance.',
  }),
  mainQuest({
    key: 'phase21_ch02_main_01',
    name: 'Ngũ Hành Sơ Vấn',
    description:
      'Mộc Thanh Y bắt đầu giảng linh căn: không hệ nào thấp hèn, chỉ đạo tâm có lệch hay không.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_chapter_02_main',
    prerequisiteQuestKey: 'phase21_ch01_main_05',
    previousQuestKey: 'phase21_ch01_main_05',
    nextQuestKey: 'phase21_ch02_main_02',
    objective: 'Nghe giảng về linh căn Ngũ Hành và chọn hướng tu đầu tiên.',
    requirement: 'Đạt Luyện Khí và hoàn thành chương 1.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_moc_thanh_y',
        count: 1,
        description: 'Nghe Mộc Thanh Y giảng về Kim, Mộc, Thuỷ, Hoả, Thổ.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_element_first_path',
        count: 1,
        description: 'Chọn hệ tu luyện biểu hiện rõ nhất của bản thân.',
      },
    ],
    rewards: {
      linhThach: 220,
      exp: 520,
      items: [{ itemKey: 'linh_lo_dan', qty: 1 }],
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 6 }],
    },
    loreSummary:
      'Expands the spiritual-root tutorial with explicit Five Elements tone.',
  }),
  mainQuest({
    key: 'phase21_ch02_main_02',
    name: 'Linh Tuyền Khai Mạch',
    description:
      'Linh Tuyền Động mở mạch khí đầu tiên, nhưng dưới dòng linh tuyền có thứ đang hút rễ cây.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_chapter_02_main',
    prerequisiteQuestKey: 'phase21_ch02_main_01',
    previousQuestKey: 'phase21_ch02_main_01',
    nextQuestKey: 'phase21_ch02_main_03',
    objective: 'Vào Hắc Lâm ven Linh Tuyền để tìm nguồn linh thảo héo.',
    requirement: 'Đã chọn hướng linh căn đầu tiên.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'hac_lam',
        count: 1,
        description: 'Khảo sát mép Hắc Lâm gần mạch Linh Tuyền.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'linh_thao',
        count: 5,
        description: 'Thu 5 gốc Linh Thảo héo để so sánh linh khí.',
      },
    ],
    rewards: {
      linhThach: 260,
      exp: 650,
      congHien: 30,
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }],
    },
    loreSummary:
      'Directly expands “Bóng đen trong Linh Điền” into the main awakening chapter.',
  }),
  mainQuest({
    key: 'phase21_ch02_main_03',
    name: 'Bóng Mộc Ăn Rễ',
    description:
      'Một yêu vật Mộc hệ đã bị Tịch Linh khí ép ăn rễ linh thảo thay vì hấp thu thiên địa.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_chapter_02_main',
    prerequisiteQuestKey: 'phase21_ch02_main_02',
    previousQuestKey: 'phase21_ch02_main_02',
    nextQuestKey: 'phase21_ch02_main_04',
    objective: 'Đánh lui yêu vật Mộc hệ và giữ lại mẫu Tịch Linh.',
    requirement: 'Đã khảo sát linh thảo héo.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'hac_yeu_xa',
        count: 3,
        description: 'Đánh bại 3 Hắc Yêu Xà bị Tịch Linh nhiễm.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'yeu_dan',
        count: 2,
        description: 'Thu 2 Yêu Đan nhiễm Mộc khí bất thường.',
      },
      {
        id: 'step_03',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Báo cáo mẫu nhiễm khí cho Lăng Vân Sinh.',
      },
    ],
    rewards: {
      linhThach: 320,
      exp: 760,
      items: [{ itemKey: 'hoi_nguyen_dan', qty: 1 }],
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }],
    },
    loreSummary:
      'Places Tịch Linh corruption into an element-coded combat problem rather than generic monsters.',
  }),
  mainQuest({
    key: 'phase21_ch02_main_04',
    name: 'Một Chiêu Hộ Tâm',
    description:
      'Muốn đi sâu hơn, Mộc Thanh Y bắt buộc người chơi học một kỹ pháp giữ tâm mạch.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_chapter_02_main',
    prerequisiteQuestKey: 'phase21_ch02_main_03',
    previousQuestKey: 'phase21_ch02_main_03',
    nextQuestKey: 'phase21_ch02_main_05',
    objective: 'Chuẩn bị kỹ pháp và đan dược trước khi xuống sâu Linh Tuyền.',
    requirement: 'Đã thu mẫu Tịch Linh nhiễm Mộc.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'linh_lo_dan',
        count: 1,
        description: 'Chuẩn bị Linh Lộ Đan để hộ tâm.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_first_skill_focus',
        count: 1,
        description: 'Chọn thiên hướng kỹ pháp đầu tiên: công, thủ hoặc hồi phục.',
      },
    ],
    rewards: {
      linhThach: 300,
      exp: 820,
      congHien: 40,
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }],
    },
    loreSummary:
      'Serves the new-player guided path requirement for learning the first skill without adding a new skill system.',
  }),
  mainQuest({
    key: 'phase21_ch02_main_05',
    name: 'Chủng Tịch Dưới Suối',
    description:
      'Mạch Linh Tuyền lộ ra một Tịch Linh Chủng non, đủ để Lăng Vân Sinh hiểu có kẻ đang nhắm vào Hoa Thiên.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_chapter_02_main',
    prerequisiteQuestKey: 'phase21_ch02_main_04',
    previousQuestKey: 'phase21_ch02_main_04',
    nextQuestKey: 'phase21_ch03_main_01',
    objective: 'Phong ấn Tịch Linh Chủng non dưới Linh Tuyền.',
    requirement: 'Đã chuẩn bị kỹ pháp hộ tâm.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'co_thu_chi_linh',
        count: 1,
        description: 'Đánh lui Cổ Thụ Chi Linh bị chủng khí thao túng.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_seal_tich_linh_seed',
        count: 1,
        description: 'Chọn phong ấn bằng linh căn bản thân hoặc bằng trận Hoa Thiên.',
      },
    ],
    rewards: {
      linhThach: 420,
      exp: 1_000,
      items: [{ itemKey: 'thanh_lam_dan', qty: 1 }],
      affinity: [
        { npcKey: 'npc_lang_van_sinh', delta: 5 },
        { npcKey: 'npc_moc_thanh_y', delta: 4 },
      ],
    },
    loreSummary:
      'Completes the awakening chapter with the first named Tịch Linh Chủng conflict.',
  }),
  mainQuest({
    key: 'phase21_ch03_main_01',
    name: 'Trận Cũ Còn Lửa',
    description:
      'Hoa Thiên Môn muốn đứng vững phải sửa lại hộ sơn trận đã nứt từ nhiều đời.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_chapter_03_main',
    prerequisiteQuestKey: 'phase21_ch02_main_05',
    previousQuestKey: 'phase21_ch02_main_05',
    nextQuestKey: 'phase21_ch03_main_02',
    objective: 'Khởi động tuyến sửa hộ sơn trận của Hoa Thiên Môn.',
    requirement: 'Đã phong ấn Tịch Linh Chủng non.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_friendly_chat'],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Nhận bản trận nứt từ Lăng Vân Sinh.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'tinh_thiet',
        count: 5,
        description: 'Chuẩn bị 5 Tinh Thiết làm đinh trận.',
      },
    ],
    rewards: {
      linhThach: 300,
      exp: 850,
      congHien: 80,
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }],
    },
    loreSummary:
      'Expands “Ngoại môn còn lửa” into a concrete sect-restoration main beat.',
  }),
  mainQuest({
    key: 'phase21_ch03_main_02',
    name: 'Đinh Trận Sơn Cốc',
    description:
      'Mỗi đinh trận cắm xuống Sơn Cốc đều cho thấy Hoa Thiên từng rộng lớn hơn bây giờ.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_chapter_03_main',
    prerequisiteQuestKey: 'phase21_ch03_main_01',
    previousQuestKey: 'phase21_ch03_main_01',
    nextQuestKey: 'phase21_ch03_main_03',
    objective: 'Cắm lại đinh trận ở Sơn Cốc và bảo vệ đệ tử phụ việc.',
    requirement: 'Đã chuẩn bị Tinh Thiết sửa trận.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'son_coc',
        count: 1,
        description: 'Tới mốc trận cũ ở Sơn Cốc.',
      },
      {
        id: 'step_02',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'da_quan',
        count: 3,
        description: 'Đánh bại 3 Đá Quan Yêu Tinh quấy phá mốc trận.',
      },
    ],
    rewards: {
      linhThach: 360,
      exp: 940,
      congHien: 90,
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 4 }],
    },
    loreSummary:
      'Ties a sect task to terrain defense and old Hoa Thiên ruins.',
  }),
  mainQuest({
    key: 'phase21_ch03_main_03',
    name: 'Kiếm Khách Huyền Kiếm',
    description:
      'Hàn Dạ đến hỏi tội Hoa Thiên vì một vết kiếm lạ, nhưng hành tung của hắn không giống kẻ địch.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_chapter_03_main',
    prerequisiteQuestKey: 'phase21_ch03_main_02',
    previousQuestKey: 'phase21_ch03_main_02',
    nextQuestKey: 'phase21_ch03_main_04',
    objective: 'Gặp Hàn Dạ và xác định hắn là rival hay manh mối.',
    requirement: 'Đã sửa mốc trận Sơn Cốc.',
    startNpcKey: 'npc_han_da',
    endNpcKey: 'npc_han_da',
    dialogueKeys: [
      'story_dlg_han_da_first_meet',
      'story_dlg_han_da_followup_neutral',
    ],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_han_da',
        count: 1,
        description: 'Đối thoại lần đầu với Hàn Dạ.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_han_da_trust_or_test',
        count: 1,
        description: 'Chọn tin Hàn Dạ hoặc yêu cầu tỷ thí trước.',
      },
    ],
    rewards: {
      linhThach: 360,
      exp: 980,
      affinity: [{ npcKey: 'npc_han_da', delta: 5 }],
    },
    loreSummary:
      'Uses the story-bible Hàn Dạ rival chain without forcing him into a flat antagonist role.',
  }),
  mainQuest({
    key: 'phase21_ch03_main_04',
    name: 'Vết Kiếm Trong Trận',
    description:
      'Vết kiếm trên hộ sơn trận giống Huyền Kiếm Tông, nhưng dưới đó lại có Tịch Linh khí.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_chapter_03_main',
    prerequisiteQuestKey: 'phase21_ch03_main_03',
    previousQuestKey: 'phase21_ch03_main_03',
    nextQuestKey: 'phase21_ch03_main_05',
    objective: 'Điều tra vết kiếm để tránh đổ oan cho Hàn Dạ.',
    requirement: 'Đã gặp Hàn Dạ.',
    startNpcKey: 'npc_han_da',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: [
      'story_dlg_han_da_followup_rival',
      'story_dlg_lang_van_sinh_inner_secret',
    ],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'tinh_thiet',
        count: 3,
        description: 'Lấy 3 mảnh Tinh Thiết bị kiếm khí cắt rời.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Đưa dấu vết về cho Lăng Vân Sinh phân biệt kiếm khí.',
      },
    ],
    rewards: {
      linhThach: 380,
      exp: 1_050,
      congHien: 100,
      affinity: [
        { npcKey: 'npc_han_da', delta: 4 },
        { npcKey: 'npc_lang_van_sinh', delta: 3 },
      ],
    },
    loreSummary:
      'Connects the rival sword clue to Tịch Thiên infiltration rather than inter-sect hostility only.',
  }),
  mainQuest({
    key: 'phase21_ch03_main_05',
    name: 'Đồng Hành Đầu Tiên',
    description:
      'Hoa Thiên cần đồng minh. Hàn Dạ chấp nhận hỗ trợ một lần nếu người chơi dám cùng hắn phá ổ yêu.',
    realmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_chapter_03_main',
    prerequisiteQuestKey: 'phase21_ch03_main_04',
    previousQuestKey: 'phase21_ch03_main_04',
    nextQuestKey: 'phase21_ch04_main_01',
    objective: 'Hoàn thành thử thách party/co-op nhẹ với Hàn Dạ.',
    requirement: 'Đã chứng minh vết kiếm không đơn giản là Huyền Kiếm gây hấn.',
    startNpcKey: 'npc_han_da',
    endNpcKey: 'npc_han_da',
    dialogueKeys: ['story_dlg_han_da_resolution_apology'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'huyet_lang',
        count: 2,
        description: 'Cùng Hàn Dạ đánh lui 2 Huyết Lang ở rìa Sơn Cốc.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_first_party_signal',
        count: 1,
        description: 'Gửi tín hiệu kết bạn/đồng hành sau trận chiến.',
      },
    ],
    rewards: {
      linhThach: 430,
      exp: 1_200,
      congHien: 110,
      affinity: [{ npcKey: 'npc_han_da', delta: 6 }],
    },
    loreSummary:
      'Satisfies the guided first-party beat while preserving Hàn Dạ’s rival-to-ally branch.',
  }),
  mainQuest({
    key: 'phase21_ch04_main_01',
    name: 'Người Giữ Giếng Cũ',
    description:
      'Tô Nguyệt Ly xuất hiện bên chiếc giếng bỏ hoang, nơi sử Hoa Thiên bị xoá khỏi ký ức tông môn.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_chapter_04_main',
    prerequisiteQuestKey: 'phase21_ch03_main_05',
    previousQuestKey: 'phase21_ch03_main_05',
    nextQuestKey: 'phase21_ch04_main_02',
    objective: 'Gặp Tô Nguyệt Ly và nhận manh mối về giếng cũ.',
    requirement: 'Đạt Trúc Cơ và hoàn thành chương Tông Môn Sơ Khởi.',
    startNpcKey: 'npc_to_nguyet_ly',
    endNpcKey: 'npc_to_nguyet_ly',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_to_nguyet_ly',
        count: 1,
        description: 'Nghe Tô Nguyệt Ly kể về nhánh Hoa Thiên lưu đày.',
      },
      {
        id: 'step_02',
        kind: 'explore',
        targetType: 'region',
        targetId: 'moc_huyen_lam',
        count: 1,
        description: 'Tìm lối mòn cũ dẫn về giếng bị dây mộc phủ kín.',
      },
    ],
    rewards: {
      linhThach: 500,
      exp: 1_500,
      affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 6 }],
    },
    loreSummary:
      'Begins the old-well inheritance chain from the story-bible quest bank.',
  }),
  mainQuest({
    key: 'phase21_ch04_main_02',
    name: 'Chìa Đá Ngũ Hành',
    description:
      'Cửa giếng cần năm dấu khí, nhưng dấu Kim và Mộc đã bị ai đó cạo khỏi mặt đá.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_chapter_04_main',
    prerequisiteQuestKey: 'phase21_ch04_main_01',
    previousQuestKey: 'phase21_ch04_main_01',
    nextQuestKey: 'phase21_ch04_main_03',
    objective: 'Khôi phục chìa đá mở bí cảnh dưới giếng.',
    requirement: 'Đã gặp Tô Nguyệt Ly.',
    startNpcKey: 'npc_to_nguyet_ly',
    endNpcKey: 'npc_to_nguyet_ly',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'phu_van_ngoc',
        count: 2,
        description: 'Thu 2 Phù Vân Ngọc khắc lại phù văn giếng cũ.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_well_element_order',
        count: 1,
        description: 'Sắp xếp thứ tự Ngũ Hành trên chìa đá.',
      },
    ],
    rewards: {
      linhThach: 560,
      exp: 1_700,
      items: [{ itemKey: 'phu_van_ngoc', qty: 1 }],
      affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }],
    },
    loreSummary:
      'Turns the old well into a Five-Element puzzle tied to erased Hoa Thiên history.',
  }),
  mainQuest({
    key: 'phase21_ch04_main_03',
    name: 'Huyết Nguyệt Khai Môn',
    description:
      'Khi chìa đá xoay đúng, ánh trăng đỏ rơi xuống đáy giếng và mở bí cảnh Huyết Nguyệt.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_chapter_04_main',
    prerequisiteQuestKey: 'phase21_ch04_main_02',
    previousQuestKey: 'phase21_ch04_main_02',
    nextQuestKey: 'phase21_ch04_main_04',
    objective: 'Mở cổng bí cảnh Huyết Nguyệt và sống sót qua đợt yêu đầu.',
    requirement: 'Đã khôi phục chìa đá Ngũ Hành.',
    startNpcKey: 'npc_to_nguyet_ly',
    endNpcKey: 'npc_to_nguyet_ly',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'moc_huyen_lam',
        count: 1,
        description: 'Bước vào cửa Huyết Nguyệt ở đáy giếng.',
      },
      {
        id: 'step_02',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'tang_diep_yeu_phu',
        count: 4,
        description: 'Đánh bại 4 Tàng Diệp Yêu Phụ giữ cổng.',
      },
    ],
    rewards: {
      linhThach: 650,
      exp: 1_950,
      items: [{ itemKey: 'co_thien_dan', qty: 1 }],
      affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 5 }],
    },
    loreSummary:
      'Introduces the Blood Moon dungeon as a hidden inheritance gate, not a random instance.',
  }),
  mainQuest({
    key: 'phase21_ch04_main_04',
    name: 'Tàn Hồn Hoa Thiên',
    description:
      'Trong bí cảnh, một tàn hồn Hoa Thiên hỏi liệu người sống đến vì truyền thừa hay vì cứu người.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_to_nguyet_ly',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_chapter_04_main',
    prerequisiteQuestKey: 'phase21_ch04_main_03',
    previousQuestKey: 'phase21_ch04_main_03',
    nextQuestKey: 'phase21_ch04_main_05',
    objective: 'Đối mặt tàn hồn Hoa Thiên và chọn cách nhận truyền thừa.',
    requirement: 'Đã mở cổng Huyết Nguyệt.',
    startNpcKey: 'npc_to_nguyet_ly',
    endNpcKey: 'npc_to_nguyet_ly',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_save_soul_or_take_relic',
        count: 1,
        description: 'Chọn cứu tàn hồn trước hay lấy pháp bảo trước.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'thien_linh_ngoc',
        count: 1,
        description: 'Thu Thiên Linh Ngọc làm chứng vật truyền thừa.',
      },
    ],
    rewards: {
      linhThach: 700,
      exp: 2_150,
      items: [{ itemKey: 'thien_linh_ngoc', qty: 1 }],
      affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 6 }],
    },
    loreSummary:
      'Preserves the story-bible moral choice: rescue remnant soul or claim treasure.',
  }),
  mainQuest({
    key: 'phase21_ch04_main_05',
    name: 'Máu Đỏ Trên Trăng',
    description:
      'Rời bí cảnh, nhóm thấy huyết nguyệt không phải điềm lành mà là dấu ai đó đang bẻ lái truyền thừa.',
    realmKey: 'truc_co',
    requiredRealmOrder: 2,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_chapter_04_main',
    prerequisiteQuestKey: 'phase21_ch04_main_04',
    previousQuestKey: 'phase21_ch04_main_04',
    nextQuestKey: 'phase21_ch05_main_01',
    objective: 'Mang chứng vật Huyết Nguyệt về Hoa Thiên Môn.',
    requirement: 'Đã gặp tàn hồn Hoa Thiên.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_inner_secret'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'kim_quang_thach_giap',
        count: 2,
        description: 'Đánh lui 2 Kim Quang Thạch Giáp bị kéo tới bởi chứng vật.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Giao Thiên Linh Ngọc cho Lăng Vân Sinh niêm phong.',
      },
    ],
    rewards: {
      linhThach: 760,
      exp: 2_400,
      congHien: 120,
      affinity: [
        { npcKey: 'npc_lang_van_sinh', delta: 4 },
        { npcKey: 'npc_to_nguyet_ly', delta: 4 },
      ],
    },
    loreSummary:
      'Completes the Blood Moon chapter and bridges toward village-bloodshed suspicion.',
  }),
  mainQuest({
    key: 'phase21_ch05_main_01',
    name: 'Thôn Dưới Thềm Đá',
    description:
      'Một thôn phụ thuộc Hoa Thiên bị diệt, để lại dấu máu giống ma đạo nhưng khí tức lại quá sạch.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_chapter_05_main',
    prerequisiteQuestKey: 'phase21_ch04_main_05',
    previousQuestKey: 'phase21_ch04_main_05',
    nextQuestKey: 'phase21_ch05_main_02',
    objective: 'Điều tra thôn bị diệt và tránh kết luận vội về ma tu.',
    requirement: 'Đạt Kim Đan và hoàn thành Huyết Nguyệt.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'explore',
        targetType: 'region',
        targetId: 'hoang_tho_huyet',
        count: 1,
        description: 'Khảo sát dấu máu ở thôn dưới thềm đá.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'huyet_tinh',
        count: 2,
        description: 'Thu 2 Huyết Tinh còn sót trên nền đá.',
      },
    ],
    rewards: {
      linhThach: 820,
      exp: 2_700,
      congHien: 130,
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }],
    },
    loreSummary:
      'Starts “Máu trên thềm đá” and preserves ambiguity between righteous and demonic paths.',
  }),
  mainQuest({
    key: 'phase21_ch05_main_02',
    name: 'Bóng Đỏ Sau Rừng',
    description:
      'Người sống sót nhắc tới một bóng áo đỏ, nhưng lời kể bị Tịch Linh khí cắt cụt.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_chapter_05_main',
    prerequisiteQuestKey: 'phase21_ch05_main_01',
    previousQuestKey: 'phase21_ch05_main_01',
    nextQuestKey: 'phase21_ch05_main_03',
    objective: 'Theo Hàn Dạ truy dấu bóng áo đỏ.',
    requirement: 'Đã khảo sát thôn dưới thềm đá.',
    startNpcKey: 'npc_han_da',
    endNpcKey: 'npc_han_da',
    dialogueKeys: ['story_dlg_han_da_followup_neutral'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'huyet_lang',
        count: 4,
        description: 'Đánh bại 4 Huyết Lang lần theo mùi máu.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_blame_demonic_path',
        count: 1,
        description: 'Chọn có đổ lỗi ngay cho ma đạo hay tiếp tục điều tra.',
      },
    ],
    rewards: {
      linhThach: 850,
      exp: 2_900,
      affinity: [{ npcKey: 'npc_han_da', delta: 4 }],
    },
    loreSummary:
      'Adds a Hàn Dạ justice lens to the massacre while avoiding one-note righteous judgment.',
  }),
  mainQuest({
    key: 'phase21_ch05_main_03',
    name: 'Huyết La Sát Hiện Thân',
    description:
      'Huyết La Sát thừa nhận từng đi qua thôn, nhưng lời của nàng không khớp với dấu Tịch Linh.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_chapter_05_main',
    prerequisiteQuestKey: 'phase21_ch05_main_02',
    previousQuestKey: 'phase21_ch05_main_02',
    nextQuestKey: 'phase21_ch05_main_04',
    objective: 'Đối chất Huyết La Sát nhưng chưa kết án.',
    requirement: 'Đã truy dấu bóng áo đỏ.',
    startNpcKey: 'npc_huyet_la_sat',
    endNpcKey: 'npc_huyet_la_sat',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_huyet_la_sat',
        count: 1,
        description: 'Đối thoại với Huyết La Sát tại huyết thạch.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_huyet_la_sat_hearing',
        count: 1,
        description: 'Chọn thái độ: chất vấn, lắng nghe hoặc rút kiếm.',
      },
    ],
    rewards: {
      linhThach: 900,
      exp: 3_100,
      affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 6 }],
    },
    loreSummary:
      'Introduces Huyết La Sát as a morally complex former Hoa Thiên-linked cultivator.',
  }),
  mainQuest({
    key: 'phase21_ch05_main_04',
    name: 'Huyết Thạch Phản Chiếu',
    description:
      'Huyết thạch ghi lại một bóng trắng dùng ma khí giả, đẩy tội cho Huyết La Sát.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_chapter_05_main',
    prerequisiteQuestKey: 'phase21_ch05_main_03',
    previousQuestKey: 'phase21_ch05_main_03',
    nextQuestKey: 'phase21_ch05_main_05',
    objective: 'Kích hoạt huyết thạch để thấy ký ức thật.',
    requirement: 'Đã đối chất Huyết La Sát.',
    startNpcKey: 'npc_huyet_la_sat',
    endNpcKey: 'npc_huyet_la_sat',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'huyet_tinh',
        count: 3,
        description: 'Dùng 3 Huyết Tinh mở phản chiếu huyết thạch.',
      },
      {
        id: 'step_02',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'kim_dieu_thuong_phong',
        count: 1,
        description: 'Đánh tan Kim Điêu Thượng Phong bị ký ức huyết thạch gọi tới.',
      },
    ],
    rewards: {
      linhThach: 980,
      exp: 3_500,
      items: [{ itemKey: 'huyet_chi_dan', qty: 1 }],
      affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }],
    },
    loreSummary:
      'Shows a false demonic trace and points the real manipulation back to Tịch Thiên.',
  }),
  mainQuest({
    key: 'phase21_ch05_main_05',
    name: 'Tha, Giết Hay Hợp Tác',
    description:
      'Huyết La Sát trao quyền phán xét. Lựa chọn không xoá tội máu, nhưng quyết định ma đạo flag sau này.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_huyet_la_sat',
    chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_chapter_05_main',
    prerequisiteQuestKey: 'phase21_ch05_main_04',
    previousQuestKey: 'phase21_ch05_main_04',
    nextQuestKey: 'phase21_ch06_main_01',
    objective: 'Đưa ra phán quyết đầu tiên với Huyết La Sát.',
    requirement: 'Đã xem phản chiếu huyết thạch.',
    startNpcKey: 'npc_huyet_la_sat',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: [],
    steps: [
      {
        id: 'step_01',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_huyet_la_sat_judgement',
        count: 1,
        description: 'Chọn tha, giết hoặc hợp tác với Huyết La Sát.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Báo lại lựa chọn cho Lăng Vân Sinh.',
      },
    ],
    rewards: {
      linhThach: 1_050,
      exp: 4_000,
      congHien: 160,
      affinity: [
        { npcKey: 'npc_huyet_la_sat', delta: 7 },
        { npcKey: 'npc_lang_van_sinh', delta: 3 },
      ],
    },
    loreSummary:
      'Completes the moral branch from “Máu trên thềm đá” without making the reward economy large.',
  }),
  mainQuest({
    key: 'phase21_ch06_main_01',
    name: 'Ngũ Hành Cộng Minh',
    description:
      'Sau lựa chọn với Huyết La Sát, Hạt Giống Vô Danh cộng hưởng với năm hệ linh khí.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_chapter_06_main',
    prerequisiteQuestKey: 'phase21_ch05_main_05',
    previousQuestKey: 'phase21_ch05_main_05',
    nextQuestKey: 'phase21_ch06_main_02',
    objective: 'Khảo nghiệm cộng hưởng Ngũ Hành của Hạt Giống Vô Danh.',
    requirement: 'Hoàn thành chương Ma Tu Xuất Thế.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'tien_kim_sa',
        count: 1,
        description: 'Chuẩn bị Tiên Kim Sa làm điểm Kim hệ.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'han_ngoc',
        count: 1,
        description: 'Chuẩn bị Hàn Ngọc làm điểm Thuỷ hệ.',
      },
    ],
    rewards: {
      linhThach: 900,
      exp: 3_700,
      congHien: 120,
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 4 }],
    },
    loreSummary:
      'Begins the Five Element heavenly mandate with real catalog materials instead of abstract lore only.',
  }),
  mainQuest({
    key: 'phase21_ch06_main_02',
    name: 'Năm Dấu Ấn Một Trận',
    description:
      'Mộc Thanh Y dựng tế đàn nhỏ để kiểm tra ngũ hành, nhưng từng dấu ấn gọi ra ký ức khác nhau.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_moc_thanh_y',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_chapter_06_main',
    prerequisiteQuestKey: 'phase21_ch06_main_01',
    previousQuestKey: 'phase21_ch06_main_01',
    nextQuestKey: 'phase21_ch06_main_03',
    objective: 'Khởi động tế đàn Ngũ Hành cùng Mộc Thanh Y.',
    requirement: 'Đã chuẩn bị vật dẫn Kim/Thuỷ.',
    startNpcKey: 'npc_moc_thanh_y',
    endNpcKey: 'npc_moc_thanh_y',
    dialogueKeys: ['story_dlg_moc_thanh_y_linh_can'],
    steps: [
      {
        id: 'step_01',
        kind: 'collect',
        targetType: 'item',
        targetId: 'linh_thao',
        count: 5,
        description: 'Đặt 5 Linh Thảo làm điểm Mộc hệ.',
      },
      {
        id: 'step_02',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_five_seal_alignment',
        count: 1,
        description: 'Cân bằng thứ tự năm dấu ấn trên tế đàn.',
      },
    ],
    rewards: {
      linhThach: 940,
      exp: 3_900,
      items: [{ itemKey: 'van_linh_dan', qty: 1 }],
      affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }],
    },
    loreSummary:
      'Keeps Mộc Thanh Y involved in the Ngũ Hành beat and links her alchemy role.',
  }),
  mainQuest({
    key: 'phase21_ch06_main_03',
    name: 'Tín Hiệu Đồng Đạo',
    description:
      'Tế đàn không thể mở một mình. Hàn Dạ và Tô Nguyệt Ly buộc phải phối hợp với Hoa Thiên.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_han_da',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_chapter_06_main',
    prerequisiteQuestKey: 'phase21_ch06_main_02',
    previousQuestKey: 'phase21_ch06_main_02',
    nextQuestKey: 'phase21_ch06_main_04',
    objective: 'Thiết lập phối hợp party/co-op cho tế đàn Ngũ Hành.',
    requirement: 'Đã cân bằng năm dấu ấn.',
    startNpcKey: 'npc_han_da',
    endNpcKey: 'npc_to_nguyet_ly',
    dialogueKeys: [
      'story_dlg_han_da_followup_neutral',
      'story_dlg_han_da_resolution_apology',
    ],
    steps: [
      {
        id: 'step_01',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_han_da',
        count: 1,
        description: 'Nhờ Hàn Dạ giữ kiếm trận phía Tây.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_to_nguyet_ly',
        count: 1,
        description: 'Nhờ Tô Nguyệt Ly đối chiếu phù văn Hoa Thiên cổ.',
      },
      {
        id: 'step_03',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_party_coop_anchor',
        count: 1,
        description: 'Chọn cách phân vai đồng đội trên tế đàn.',
      },
    ],
    rewards: {
      linhThach: 980,
      exp: 4_100,
      congHien: 150,
      affinity: [
        { npcKey: 'npc_han_da', delta: 4 },
        { npcKey: 'npc_to_nguyet_ly', delta: 4 },
      ],
    },
    loreSummary:
      'Satisfies party/co-op story binding by making allies necessary for the Five Element ritual.',
  }),
  mainQuest({
    key: 'phase21_ch06_main_04',
    name: 'Long Điêu Kim Phách',
    description:
      'Kim hệ trên tế đàn mất kiểm soát, gọi tới Long Điêu mang kim phách bị Tịch Linh bám rễ.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_chapter_06_main',
    prerequisiteQuestKey: 'phase21_ch06_main_03',
    previousQuestKey: 'phase21_ch06_main_03',
    nextQuestKey: 'phase21_ch06_main_05',
    objective: 'Đánh bại Kim hệ boss-bound encounter để giữ tế đàn.',
    requirement: 'Đã phân vai đồng đội trên tế đàn.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: ['story_dlg_lang_van_sinh_seed_truth'],
    steps: [
      {
        id: 'step_01',
        kind: 'kill',
        targetType: 'monster',
        targetId: 'kim_dieu_thuong_phong',
        count: 1,
        description: 'Đánh bại Kim Điêu Thượng Phong giữ kim phách.',
      },
      {
        id: 'step_02',
        kind: 'collect',
        targetType: 'item',
        targetId: 'tien_kim_sa',
        count: 2,
        description: 'Thu 2 Tiên Kim Sa sau khi kim khí lắng xuống.',
      },
    ],
    rewards: {
      linhThach: 1_080,
      exp: 4_500,
      items: [{ itemKey: 'skill_book_kim_quang_tram', qty: 1 }],
      affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }],
    },
    loreSummary:
      'Binds the Kim Phách Long Điêu boss identity to Ngũ Hành ritual escalation.',
  }),
  mainQuest({
    key: 'phase21_ch06_main_05',
    name: 'Thiên Mệnh Chưa Thành',
    description:
      'Tế đàn chỉ mở ra một tiếng vọng: Tịch Thiên đã nhìn thấy Hạt Giống Vô Danh.',
    realmKey: 'kim_dan',
    requiredRealmOrder: 3,
    giverNpcKey: 'npc_lang_van_sinh',
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_chapter_06_main',
    prerequisiteQuestKey: 'phase21_ch06_main_04',
    previousQuestKey: 'phase21_ch06_main_04',
    nextQuestKey: null,
    objective: 'Khép lại Phase 21 main chain và mở foreshadow Tịch Thiên tuyến.',
    requirement: 'Đã ổn định Long Điêu Kim Phách.',
    startNpcKey: 'npc_lang_van_sinh',
    endNpcKey: 'npc_lang_van_sinh',
    dialogueKeys: [
      'story_dlg_lang_van_sinh_seed_truth',
      'story_dlg_lang_van_sinh_inner_secret',
    ],
    steps: [
      {
        id: 'step_01',
        kind: 'choice',
        targetType: 'choice',
        targetId: 'choice_phase21_heavenly_mandate_oath',
        count: 1,
        description: 'Lập lời thề giữ Hạt Giống Vô Danh khỏi Tịch Thiên.',
      },
      {
        id: 'step_02',
        kind: 'talk',
        targetType: 'npc',
        targetId: 'npc_lang_van_sinh',
        count: 1,
        description: 'Nghe Lăng Vân Sinh nói về cái tên Tịch Thiên Điện.',
      },
    ],
    rewards: {
      linhThach: 1_250,
      exp: 5_000,
      congHien: 200,
      items: [{ itemKey: 'co_thien_dan', qty: 1 }],
      affinity: [
        { npcKey: 'npc_lang_van_sinh', delta: 6 },
        { npcKey: 'npc_moc_thanh_y', delta: 4 },
      ],
    },
    loreSummary:
      'Ends Phase 21 on a clear forward hook: Tịch Thiên notices the Nameless Seed, but the late-game twist remains preserved.',
  }),
] as const;
