import type { QuestDef, QuestRewardDef, QuestStepDef } from './quests';

interface Phase21HiddenQuestInput { key: string; name: string; description: string; realmKey: string; requiredRealmOrder: number; giverNpcKey: string; chapterKey: string; chainKey: string; prerequisiteQuestKey: string; objective: string; requirement: string; trigger: string; steps: readonly QuestStepDef[]; rewards: QuestRewardDef; loreSummary: string; }
function hiddenQuest(input: Phase21HiddenQuestInput): QuestDef { return { ...input, kind: 'hidden' }; }
export const PHASE21_HIDDEN_QUESTS: readonly QuestDef[] = [
  hiddenQuest({
    key: 'phase21_hidden_001',
    name: 'Phàm Nhân Nhập Đạo: Ẩn lương khô tân đệ tử 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý lương khô tân đệ tử bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_hidden_ch01_1', prerequisiteQuestKey: 'phase21_ch01_main_03',
    objective: 'Hoàn thành khám phá ẩn về lương khô tân đệ tử.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_pham_nhan_nhap_dao; theme=lương khô tân đệ tử',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'yeu_thu_dong', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 38, exp: 83, congHien: 6, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với lương khô tân đệ tử; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_002',
    name: 'Phàm Nhân Nhập Đạo: Ẩn Sơn Cốc bất ổn 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Sơn Cốc bất ổn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_hidden_ch01_2', prerequisiteQuestKey: 'phase21_ch01_main_05',
    objective: 'Hoàn thành khám phá ẩn về Sơn Cốc bất ổn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_pham_nhan_nhap_dao; theme=Sơn Cốc bất ổn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 40, exp: 88, congHien: 6, affinity: [{ npcKey: 'npc_a_linh', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Sơn Cốc bất ổn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_003',
    name: 'Phàm Nhân Nhập Đạo: Ẩn đời sống ngoại môn 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đời sống ngoại môn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_hidden_ch01_3', prerequisiteQuestKey: 'phase21_ch01_main_07',
    objective: 'Hoàn thành khám phá ẩn về đời sống ngoại môn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_pham_nhan_nhap_dao; theme=đời sống ngoại môn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'kim_son_mach', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'yeu_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 40, exp: 93, congHien: 7, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đời sống ngoại môn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_004',
    name: 'Phàm Nhân Nhập Đạo: Ẩn đèn tổ sư 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đèn tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_hidden_ch01_0', prerequisiteQuestKey: 'phase21_ch01_main_09',
    objective: 'Hoàn thành khám phá ẩn về đèn tổ sư.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_pham_nhan_nhap_dao; theme=đèn tổ sư',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'thuy_long_uyen', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'huyet_tinh', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 42, exp: 98, congHien: 7, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đèn tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_005',
    name: 'Phàm Nhân Nhập Đạo: Ẩn lương khô tân đệ tử 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý lương khô tân đệ tử bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'phamnhan', requiredRealmOrder: 0, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_pham_nhan_nhap_dao',
    chainKey: 'phase21_hidden_ch01_1', prerequisiteQuestKey: 'phase21_ch01_main_11',
    objective: 'Hoàn thành khám phá ẩn về lương khô tân đệ tử.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_pham_nhan_nhap_dao; theme=lương khô tân đệ tử',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoa_diem_son', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 44, exp: 104, congHien: 8, affinity: [{ npcKey: 'npc_a_linh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với lương khô tân đệ tử; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_006',
    name: 'Linh Căn Thức Tỉnh: Ẩn Tịch Linh vết mờ 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Tịch Linh vết mờ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_hidden_ch02_1', prerequisiteQuestKey: 'phase21_ch02_main_03',
    objective: 'Hoàn thành khám phá ẩn về Tịch Linh vết mờ.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_linh_can_thuc_tinh; theme=Tịch Linh vết mờ',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 51, exp: 122, congHien: 8, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Tịch Linh vết mờ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_007',
    name: 'Linh Căn Thức Tỉnh: Ẩn lò đan thiếu dược 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý lò đan thiếu dược bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_hidden_ch02_2', prerequisiteQuestKey: 'phase21_ch02_main_05',
    objective: 'Hoàn thành khám phá ẩn về lò đan thiếu dược.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_linh_can_thuc_tinh; theme=lò đan thiếu dược',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'kim_son_mach', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'yeu_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 52, exp: 128, congHien: 8, affinity: [{ npcKey: 'npc_a_linh', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với lò đan thiếu dược; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_008',
    name: 'Linh Căn Thức Tỉnh: Ẩn linh căn lệch nhịp 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý linh căn lệch nhịp bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_hidden_ch02_3', prerequisiteQuestKey: 'phase21_ch02_main_07',
    objective: 'Hoàn thành khám phá ẩn về linh căn lệch nhịp.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_linh_can_thuc_tinh; theme=linh căn lệch nhịp',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'thuy_long_uyen', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'huyet_tinh', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 53, exp: 133, congHien: 9, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với linh căn lệch nhịp; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_009',
    name: 'Linh Căn Thức Tỉnh: Ẩn Ngũ Hành sơ cảm 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Ngũ Hành sơ cảm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_hidden_ch02_0', prerequisiteQuestKey: 'phase21_ch02_main_09',
    objective: 'Hoàn thành khám phá ẩn về Ngũ Hành sơ cảm.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_linh_can_thuc_tinh; theme=Ngũ Hành sơ cảm',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoa_diem_son', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 55, exp: 137, congHien: 9, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Ngũ Hành sơ cảm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_010',
    name: 'Linh Căn Thức Tỉnh: Ẩn Tịch Linh vết mờ 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Tịch Linh vết mờ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_a_linh', chapterKey: 'chapter_linh_can_thuc_tinh',
    chainKey: 'phase21_hidden_ch02_1', prerequisiteQuestKey: 'phase21_ch02_main_11',
    objective: 'Hoàn thành khám phá ẩn về Tịch Linh vết mờ.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_linh_can_thuc_tinh; theme=Tịch Linh vết mờ',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoang_tho_huyet', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 56, exp: 142, congHien: 10, affinity: [{ npcKey: 'npc_a_linh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Tịch Linh vết mờ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_011',
    name: 'Tông Môn Sơ Khởi: Ẩn Vạn Bảo giao kèo 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Vạn Bảo giao kèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_hidden_ch03_1', prerequisiteQuestKey: 'phase21_ch03_main_03',
    objective: 'Hoàn thành khám phá ẩn về Vạn Bảo giao kèo.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tong_mon_so_khoi; theme=Vạn Bảo giao kèo',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'kim_son_mach', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'yeu_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 63, exp: 162, congHien: 10, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Vạn Bảo giao kèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_012',
    name: 'Tông Môn Sơ Khởi: Ẩn trận kỳ cũ 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý trận kỳ cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_van_kim_nuong', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_hidden_ch03_2', prerequisiteQuestKey: 'phase21_ch03_main_05',
    objective: 'Hoàn thành khám phá ẩn về trận kỳ cũ.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tong_mon_so_khoi; theme=trận kỳ cũ',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'thuy_long_uyen', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'huyet_tinh', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 64, exp: 166, congHien: 10, affinity: [{ npcKey: 'npc_van_kim_nuong', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với trận kỳ cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_013',
    name: 'Tông Môn Sơ Khởi: Ẩn tông môn nghèo 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý tông môn nghèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_hidden_ch03_3', prerequisiteQuestKey: 'phase21_ch03_main_07',
    objective: 'Hoàn thành khám phá ẩn về tông môn nghèo.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tong_mon_so_khoi; theme=tông môn nghèo',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoa_diem_son', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 65, exp: 172, congHien: 10, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với tông môn nghèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_014',
    name: 'Tông Môn Sơ Khởi: Ẩn Hàn Dạ khiêu chiến 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Hàn Dạ khiêu chiến bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_hidden_ch03_0', prerequisiteQuestKey: 'phase21_ch03_main_09',
    objective: 'Hoàn thành khám phá ẩn về Hàn Dạ khiêu chiến.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tong_mon_so_khoi; theme=Hàn Dạ khiêu chiến',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoang_tho_huyet', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 67, exp: 176, congHien: 11, affinity: [{ npcKey: 'npc_han_da', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Hàn Dạ khiêu chiến; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_015',
    name: 'Tông Môn Sơ Khởi: Ẩn Vạn Bảo giao kèo 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Vạn Bảo giao kèo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'luyenkhi', requiredRealmOrder: 1, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tong_mon_so_khoi',
    chainKey: 'phase21_hidden_ch03_1', prerequisiteQuestKey: 'phase21_ch03_main_11',
    objective: 'Hoàn thành khám phá ẩn về Vạn Bảo giao kèo.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tong_mon_so_khoi; theme=Vạn Bảo giao kèo',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 68, exp: 182, congHien: 11, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Vạn Bảo giao kèo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_016',
    name: 'Bí Cảnh Huyết Nguyệt: Ẩn ký ức tổ sư 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý ký ức tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_hidden_ch04_1', prerequisiteQuestKey: 'phase21_ch04_main_03',
    objective: 'Hoàn thành khám phá ẩn về ký ức tổ sư.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_bi_canh_huyet_nguyet; theme=ký ức tổ sư',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'thuy_long_uyen', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'huyet_tinh', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 76, exp: 201, congHien: 12, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với ký ức tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_017',
    name: 'Bí Cảnh Huyết Nguyệt: Ẩn dấu phong ấn 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý dấu phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_hidden_ch04_2', prerequisiteQuestKey: 'phase21_ch04_main_05',
    objective: 'Hoàn thành khám phá ẩn về dấu phong ấn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_bi_canh_huyet_nguyet; theme=dấu phong ấn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoa_diem_son', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 76, exp: 206, congHien: 13, affinity: [{ npcKey: 'npc_han_da', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với dấu phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_018',
    name: 'Bí Cảnh Huyết Nguyệt: Ẩn trăng máu còn sót 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý trăng máu còn sót bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_hidden_ch04_3', prerequisiteQuestKey: 'phase21_ch04_main_07',
    objective: 'Hoàn thành khám phá ẩn về trăng máu còn sót.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_bi_canh_huyet_nguyet; theme=trăng máu còn sót',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoang_tho_huyet', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 78, exp: 211, congHien: 13, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với trăng máu còn sót; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_019',
    name: 'Bí Cảnh Huyết Nguyệt: Ẩn giếng cổ đổi màu 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý giếng cổ đổi màu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_hidden_ch04_0', prerequisiteQuestKey: 'phase21_ch04_main_09',
    objective: 'Hoàn thành khám phá ẩn về giếng cổ đổi màu.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_bi_canh_huyet_nguyet; theme=giếng cổ đổi màu',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 80, exp: 216, congHien: 14, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với giếng cổ đổi màu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_020',
    name: 'Bí Cảnh Huyết Nguyệt: Ẩn ký ức tổ sư 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý ký ức tổ sư bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_bi_canh_huyet_nguyet',
    chainKey: 'phase21_hidden_ch04_1', prerequisiteQuestKey: 'phase21_ch04_main_11',
    objective: 'Hoàn thành khám phá ẩn về ký ức tổ sư.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_bi_canh_huyet_nguyet; theme=ký ức tổ sư',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 80, exp: 220, congHien: 14, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với ký ức tổ sư; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_021',
    name: 'Ma Tu Xuất Thế: Ẩn đạo tâm lựa chọn 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đạo tâm lựa chọn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_hidden_ch05_1', prerequisiteQuestKey: 'phase21_ch05_main_03',
    objective: 'Hoàn thành khám phá ẩn về đạo tâm lựa chọn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ma_tu_xuat_the; theme=đạo tâm lựa chọn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoa_diem_son', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_lo_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 88, exp: 240, congHien: 14, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đạo tâm lựa chọn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_022',
    name: 'Ma Tu Xuất Thế: Ẩn huyết khí mất kiểm 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý huyết khí mất kiểm bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_ha_su_gia', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_hidden_ch05_2', prerequisiteQuestKey: 'phase21_ch05_main_05',
    objective: 'Hoàn thành khám phá ẩn về huyết khí mất kiểm.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ma_tu_xuat_the; theme=huyết khí mất kiểm',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoang_tho_huyet', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 89, exp: 245, congHien: 14, affinity: [{ npcKey: 'npc_huyet_ha_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với huyết khí mất kiểm; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_023',
    name: 'Ma Tu Xuất Thế: Ẩn Huyết Hà nhân chứng 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Huyết Hà nhân chứng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_han_da', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_hidden_ch05_3', prerequisiteQuestKey: 'phase21_ch05_main_07',
    objective: 'Hoàn thành khám phá ẩn về Huyết Hà nhân chứng.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ma_tu_xuat_the; theme=Huyết Hà nhân chứng',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 90, exp: 250, congHien: 15, affinity: [{ npcKey: 'npc_han_da', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Huyết Hà nhân chứng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_024',
    name: 'Ma Tu Xuất Thế: Ẩn ma tu bị oan 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý ma tu bị oan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_hidden_ch05_0', prerequisiteQuestKey: 'phase21_ch05_main_09',
    objective: 'Hoàn thành khám phá ẩn về ma tu bị oan.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ma_tu_xuat_the; theme=ma tu bị oan',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 92, exp: 255, congHien: 15, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với ma tu bị oan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_025',
    name: 'Ma Tu Xuất Thế: Ẩn đạo tâm lựa chọn 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đạo tâm lựa chọn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'truc_co', requiredRealmOrder: 2, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ma_tu_xuat_the',
    chainKey: 'phase21_hidden_ch05_1', prerequisiteQuestKey: 'phase21_ch05_main_11',
    objective: 'Hoàn thành khám phá ẩn về đạo tâm lựa chọn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ma_tu_xuat_the; theme=đạo tâm lựa chọn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'yeu_thu_dong', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 93, exp: 260, congHien: 16, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đạo tâm lựa chọn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_026',
    name: 'Ngũ Hành Thiên Mệnh: Ẩn Tịch Thiên tín hiệu 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Tịch Thiên tín hiệu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_hidden_ch06_1', prerequisiteQuestKey: 'phase21_ch06_main_03',
    objective: 'Hoàn thành khám phá ẩn về Tịch Thiên tín hiệu.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ngu_hanh_thien_menh; theme=Tịch Thiên tín hiệu',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hoang_tho_huyet', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'hoi_nguyen_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 100, exp: 279, congHien: 16, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Tịch Thiên tín hiệu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_027',
    name: 'Ngũ Hành Thiên Mệnh: Ẩn đồng đội hợp lực 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đồng đội hợp lực bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_to_nguyet_ly', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_hidden_ch06_2', prerequisiteQuestKey: 'phase21_ch06_main_05',
    objective: 'Hoàn thành khám phá ẩn về đồng đội hợp lực.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ngu_hanh_thien_menh; theme=đồng đội hợp lực',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 101, exp: 284, congHien: 16, affinity: [{ npcKey: 'npc_to_nguyet_ly', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đồng đội hợp lực; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_028',
    name: 'Ngũ Hành Thiên Mệnh: Ẩn Ngũ Hành cộng hưởng 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Ngũ Hành cộng hưởng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_huyet_la_sat', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_hidden_ch06_3', prerequisiteQuestKey: 'phase21_ch06_main_07',
    objective: 'Hoàn thành khám phá ẩn về Ngũ Hành cộng hưởng.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ngu_hanh_thien_menh; theme=Ngũ Hành cộng hưởng',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 103, exp: 290, congHien: 17, affinity: [{ npcKey: 'npc_huyet_la_sat', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Ngũ Hành cộng hưởng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_029',
    name: 'Ngũ Hành Thiên Mệnh: Ẩn đàn tế Kim Đan 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đàn tế Kim Đan bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_hidden_ch06_0', prerequisiteQuestKey: 'phase21_ch06_main_09',
    objective: 'Hoàn thành khám phá ẩn về đàn tế Kim Đan.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ngu_hanh_thien_menh; theme=đàn tế Kim Đan',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'yeu_thu_dong', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 104, exp: 294, congHien: 17, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đàn tế Kim Đan; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_030',
    name: 'Ngũ Hành Thiên Mệnh: Ẩn Tịch Thiên tín hiệu 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Tịch Thiên tín hiệu bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'kim_dan', requiredRealmOrder: 3, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_ngu_hanh_thien_menh',
    chainKey: 'phase21_hidden_ch06_1', prerequisiteQuestKey: 'phase21_ch06_main_11',
    objective: 'Hoàn thành khám phá ẩn về Tịch Thiên tín hiệu.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_ngu_hanh_thien_menh; theme=Tịch Thiên tín hiệu',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 105, exp: 299, congHien: 18, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Tịch Thiên tín hiệu; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_031',
    name: 'Tâm Ma Của Đại Sư Tỷ: Ẩn ký ức bị khoá 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý ký ức bị khoá bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_hidden_ch07_1', prerequisiteQuestKey: 'phase21_ch07_main_03',
    objective: 'Hoàn thành khám phá ẩn về ký ức bị khoá.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tam_ma_dai_su_ty; theme=ký ức bị khoá',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'son_coc', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'thanh_lam_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 112, exp: 319, congHien: 18, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với ký ức bị khoá; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_032',
    name: 'Tâm Ma Của Đại Sư Tỷ: Ẩn lời thề hộ đạo 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý lời thề hộ đạo bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_hidden_ch07_2', prerequisiteQuestKey: 'phase21_ch07_main_05',
    objective: 'Hoàn thành khám phá ẩn về lời thề hộ đạo.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tam_ma_dai_su_ty; theme=lời thề hộ đạo',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 114, exp: 323, congHien: 19, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với lời thề hộ đạo; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_033',
    name: 'Tâm Ma Của Đại Sư Tỷ: Ẩn tâm ma Mộc Thanh Y 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý tâm ma Mộc Thanh Y bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_moc_thanh_y', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_hidden_ch07_3', prerequisiteQuestKey: 'phase21_ch07_main_07',
    objective: 'Hoàn thành khám phá ẩn về tâm ma Mộc Thanh Y.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tam_ma_dai_su_ty; theme=tâm ma Mộc Thanh Y',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'yeu_thu_dong', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 115, exp: 328, congHien: 19, affinity: [{ npcKey: 'npc_moc_thanh_y', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với tâm ma Mộc Thanh Y; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_034',
    name: 'Tâm Ma Của Đại Sư Tỷ: Ẩn Tịch Linh Chủng 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Tịch Linh Chủng bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_hidden_ch07_0', prerequisiteQuestKey: 'phase21_ch07_main_09',
    objective: 'Hoàn thành khám phá ẩn về Tịch Linh Chủng.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tam_ma_dai_su_ty; theme=Tịch Linh Chủng',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 116, exp: 333, congHien: 20, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Tịch Linh Chủng; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_035',
    name: 'Tâm Ma Của Đại Sư Tỷ: Ẩn ký ức bị khoá 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý ký ức bị khoá bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'nguyen_anh', requiredRealmOrder: 4, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_tam_ma_dai_su_ty',
    chainKey: 'phase21_hidden_ch07_1', prerequisiteQuestKey: 'phase21_ch07_main_11',
    objective: 'Hoàn thành khám phá ẩn về ký ức bị khoá.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_tam_ma_dai_su_ty; theme=ký ức bị khoá',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'kim_son_mach', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 118, exp: 338, congHien: 20, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với ký ức bị khoá; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_036',
    name: 'Hoa Thiên Sơn Tầng Một: Ẩn kinh lâu cũ 1',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý kinh lâu cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_hoa_thien_dao_to', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_hidden_ch08_1', prerequisiteQuestKey: 'phase21_ch08_main_03',
    objective: 'Hoàn thành khám phá ẩn về kinh lâu cũ.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_hoa_thien_son_tang_mot; theme=kinh lâu cũ',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'hac_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'linh_thao', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 125, exp: 358, congHien: 20, affinity: [{ npcKey: 'npc_hoa_thien_dao_to', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với kinh lâu cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_037',
    name: 'Hoa Thiên Sơn Tầng Một: Ẩn sứ giả Tịch Thiên 2',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý sứ giả Tịch Thiên bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_hidden_ch08_2', prerequisiteQuestKey: 'phase21_ch08_main_05',
    objective: 'Hoàn thành khám phá ẩn về sứ giả Tịch Thiên.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_hoa_thien_son_tang_mot; theme=sứ giả Tịch Thiên',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'yeu_thu_dong', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'tinh_thiet', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 126, exp: 362, congHien: 21, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 4 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với sứ giả Tịch Thiên; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_038',
    name: 'Hoa Thiên Sơn Tầng Một: Ẩn Hoa Thiên Sơn phong ấn 3',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý Hoa Thiên Sơn phong ấn bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_lang_van_sinh', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_hidden_ch08_3', prerequisiteQuestKey: 'phase21_ch08_main_07',
    objective: 'Hoàn thành khám phá ẩn về Hoa Thiên Sơn phong ấn.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_hoa_thien_son_tang_mot; theme=Hoa Thiên Sơn phong ấn',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'moc_huyen_lam', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'phu_van_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 128, exp: 368, congHien: 21, affinity: [{ npcKey: 'npc_lang_van_sinh', delta: 5 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với Hoa Thiên Sơn phong ấn; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_039',
    name: 'Hoa Thiên Sơn Tầng Một: Ẩn đạo thống tầng một 4',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý đạo thống tầng một bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_hoa_thien_dao_to', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_hidden_ch08_0', prerequisiteQuestKey: 'phase21_ch08_main_09',
    objective: 'Hoàn thành khám phá ẩn về đạo thống tầng một.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_hoa_thien_son_tang_mot; theme=đạo thống tầng một',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'kim_son_mach', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'han_ngoc', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 129, exp: 373, congHien: 22, affinity: [{ npcKey: 'npc_hoa_thien_dao_to', delta: 2 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với đạo thống tầng một; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
  hiddenQuest({
    key: 'phase21_hidden_040',
    name: 'Hoa Thiên Sơn Tầng Một: Ẩn kinh lâu cũ 5',
    description: 'Hidden quest mở khi hidden trigger via item/realm/affinity/dungeon condition, xử lý kinh lâu cũ bằng một kết quả có hậu quả nhỏ.',
    realmKey: 'hoa_than', requiredRealmOrder: 5, giverNpcKey: 'npc_tich_linh_su_gia', chapterKey: 'chapter_hoa_thien_son_tang_mot',
    chainKey: 'phase21_hidden_ch08_1', prerequisiteQuestKey: 'phase21_ch08_main_11',
    objective: 'Hoàn thành khám phá ẩn về kinh lâu cũ.', requirement: 'Cần hidden trigger via item/realm/affinity/dungeon condition và tiến trình chương tương ứng.',
    trigger: 'hidden trigger via item/realm/affinity/dungeon condition; chapter=chapter_hoa_thien_son_tang_mot; theme=kinh lâu cũ',
    steps: [{ id: 'step_01', kind: 'explore', targetType: 'region', targetId: 'thuy_long_uyen', count: 1, description: 'Tìm dấu hiệu ẩn chỉ hiện khi đủ trigger.' }, { id: 'step_02', kind: 'collect', targetType: 'item', targetId: 'yeu_dan', count: 1, description: 'Nhặt lore fragment hoặc vật dẫn nhỏ, không phá economy.' }],
    rewards: { linhThach: 130, exp: 377, congHien: 22, affinity: [{ npcKey: 'npc_tich_linh_su_gia', delta: 3 }] },
    loreSummary: 'AI_EXPANDED_LORE: Hidden content gắn với kinh lâu cũ; reward bị cap, ưu tiên affinity/dialogue/lore hơn currency.',
  }),
];
