import type { ElementKey } from './combat';

export interface StoryChapterUnlockCondition { kind: 'realm' | 'quest_claimed' | 'story_flag' | 'multi_gate'; realmKey?: string; questKey?: string; flagKey?: string; descriptionVi: string; descriptionEn: string; }
export type StoryChapterGateRuntimeStatus = 'runtime_enforced' | 'catalog_seeded_runtime_follow_up';
export interface StoryChapterUnlockGate { requiredRealmKey: string; requiredRealmOrder: number; requiredCultivationStage?: number | null; requiredBattlePower?: number | null; requiredMainQuestKey?: string | null; previousChapterKey?: string | null; requiredStoryFlag?: string | null; requiredDungeonClearKey?: string | null; requiredBossDefeatedKey?: string | null; requiredSectRank?: string | null; requiredElementalAffinity?: ElementKey | 'any' | null; runtimeStatus: StoryChapterGateRuntimeStatus; descriptionVi: string; descriptionEn: string; }
export interface StoryChapterReward { linhThach?: number; exp?: number; congHien?: number; items?: ReadonlyArray<{ itemKey: string; qty: number }>; achievementKeys?: readonly string[]; titleKeys?: readonly string[]; }
export interface StoryChapterDef { chapterKey: string; order: number; titleVi: string; titleEn: string; descriptionVi: string; descriptionEn: string; unlockCondition: StoryChapterUnlockCondition; unlockGate: StoryChapterUnlockGate; requiredRealmKey: string; requiredRealmOrder: number; mainQuestChainKey: string; mainQuestKeys: readonly string[]; involvedNpcKeys: readonly string[]; relatedDungeonKeys: readonly string[]; relatedBossKeys: readonly string[]; chapterReward: StoryChapterReward; loreSummary: string; }

export const STORY_CHAPTERS: readonly StoryChapterDef[] = [
  {
    chapterKey: 'chapter_pham_nhan_nhap_dao',
    order: 1,
    titleVi: 'Phàm Nhân Nhập Đạo',
    titleEn: 'Mortal Enters the Dao',
    descriptionVi: 'Phàm Nhân Nhập Đạo mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Mortal Enters the Dao opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'realm', realmKey: 'phamnhan', descriptionVi: 'Mở khi tạo nhân vật Phàm Nhân.', descriptionEn: 'Unlocked for a new Mortal character.' },
    unlockGate: {
      requiredRealmKey: 'phamnhan', requiredRealmOrder: 0, requiredCultivationStage: 1, requiredBattlePower: 0, requiredMainQuestKey: null, previousChapterKey: null, requiredStoryFlag: 'story_flag_character_created', requiredDungeonClearKey: null, requiredBossDefeatedKey: null, requiredSectRank: null, requiredElementalAffinity: null, runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 1: cần phamnhan, tầng 1, lực chiến 0, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 1 gate: requires phamnhan, stage 1, battle power 0, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'phamnhan',
    requiredRealmOrder: 0,
    mainQuestChainKey: 'phase21_chapter_01_main',
    mainQuestKeys: ['phase21_ch01_main_01', 'phase21_ch01_main_02', 'phase21_ch01_main_03', 'phase21_ch01_main_04', 'phase21_ch01_main_05', 'phase21_ch01_main_06', 'phase21_ch01_main_07', 'phase21_ch01_main_08', 'phase21_ch01_main_09', 'phase21_ch01_main_10', 'phase21_ch01_main_11', 'phase21_ch01_main_12', 'phase21_ch01_main_13', 'phase21_ch01_main_14', 'phase21_ch01_main_15'],
    involvedNpcKeys: ['npc_lang_van_sinh', 'npc_moc_thanh_y', 'npc_a_linh'],
    relatedDungeonKeys: ['story_dgn_phamnhan_back_mountain'],
    relatedBossKeys: [],
    chapterReward: { linhThach: 340, exp: 950, congHien: 55, items: [{ itemKey: 'so_kiem', qty: 1 }], achievementKeys: ['phase21_story_chapter_01_complete'], titleKeys: ['phase21_title_hoa_thien_tan_do'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE: Hoa Thiên admission, A Linh onboarding, and the first Nameless Seed hint.',
  },
  {
    chapterKey: 'chapter_linh_can_thuc_tinh',
    order: 2,
    titleVi: 'Linh Căn Thức Tỉnh',
    titleEn: 'Spiritual Root Awakening',
    descriptionVi: 'Linh Căn Thức Tỉnh mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Spiritual Root Awakening opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch01_main_15', descriptionVi: 'Hoàn thành chương 1 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 1 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'luyenkhi', requiredRealmOrder: 1, requiredCultivationStage: 1, requiredBattlePower: 850, requiredMainQuestKey: 'phase21_ch01_main_15', previousChapterKey: 'chapter_pham_nhan_nhap_dao', requiredStoryFlag: 'story_flag_seed_truth_heard', requiredDungeonClearKey: 'story_dgn_phamnhan_back_mountain', requiredBossDefeatedKey: null, requiredSectRank: 'ngoai_mon', requiredElementalAffinity: 'any', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 2: cần luyenkhi, tầng 1, lực chiến 850, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 2 gate: requires luyenkhi, stage 1, battle power 850, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    mainQuestChainKey: 'phase21_chapter_02_main',
    mainQuestKeys: ['phase21_ch02_main_01', 'phase21_ch02_main_02', 'phase21_ch02_main_03', 'phase21_ch02_main_04', 'phase21_ch02_main_05', 'phase21_ch02_main_06', 'phase21_ch02_main_07', 'phase21_ch02_main_08', 'phase21_ch02_main_09', 'phase21_ch02_main_10', 'phase21_ch02_main_11', 'phase21_ch02_main_12', 'phase21_ch02_main_13', 'phase21_ch02_main_14', 'phase21_ch02_main_15'],
    involvedNpcKeys: ['npc_moc_thanh_y', 'npc_lang_van_sinh', 'npc_a_linh'],
    relatedDungeonKeys: ['story_dgn_luyenkhi_hac_lam_trial'],
    relatedBossKeys: [],
    chapterReward: { linhThach: 500, exp: 1600, congHien: 80, items: [{ itemKey: 'linh_lo_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_02_complete'], titleKeys: ['phase21_title_linh_can_so_tinh'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE: spiritual-root teaching, Five Element choice, and Tịch Linh Chủng foreshadow around Mộc Thanh Y.',
  },
  {
    chapterKey: 'chapter_tong_mon_so_khoi',
    order: 3,
    titleVi: 'Tông Môn Sơ Khởi',
    titleEn: 'Sect Foundations',
    descriptionVi: 'Tông Môn Sơ Khởi mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Sect Foundations opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch02_main_15', descriptionVi: 'Hoàn thành chương 2 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 2 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'luyenkhi', requiredRealmOrder: 1, requiredCultivationStage: 4, requiredBattlePower: 1400, requiredMainQuestKey: 'phase21_ch02_main_15', previousChapterKey: 'chapter_linh_can_thuc_tinh', requiredStoryFlag: 'story_flag_linh_can_awakened', requiredDungeonClearKey: 'story_dgn_luyenkhi_hac_lam_trial', requiredBossDefeatedKey: null, requiredSectRank: 'ngoai_mon', requiredElementalAffinity: 'any', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 3: cần luyenkhi, tầng 4, lực chiến 1400, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 3 gate: requires luyenkhi, stage 4, battle power 1400, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'luyenkhi',
    requiredRealmOrder: 1,
    mainQuestChainKey: 'phase21_chapter_03_main',
    mainQuestKeys: ['phase21_ch03_main_01', 'phase21_ch03_main_02', 'phase21_ch03_main_03', 'phase21_ch03_main_04', 'phase21_ch03_main_05', 'phase21_ch03_main_06', 'phase21_ch03_main_07', 'phase21_ch03_main_08', 'phase21_ch03_main_09', 'phase21_ch03_main_10', 'phase21_ch03_main_11', 'phase21_ch03_main_12', 'phase21_ch03_main_13', 'phase21_ch03_main_14', 'phase21_ch03_main_15'],
    involvedNpcKeys: ['npc_lang_van_sinh', 'npc_moc_thanh_y', 'npc_han_da', 'npc_van_kim_nuong'],
    relatedDungeonKeys: ['story_dgn_truc_co_co_thu_ky'],
    relatedBossKeys: [],
    chapterReward: { linhThach: 660, exp: 2250, congHien: 105, items: [{ itemKey: 'hoi_nguyen_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_03_complete'], titleKeys: ['phase21_title_ngoai_mon_tru_cot'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE + AI_EXPANDED_LORE: sect contribution, Hàn Dạ rivalry, Vạn Bảo errands, and social tutorial hooks.',
  },
  {
    chapterKey: 'chapter_bi_canh_huyet_nguyet',
    order: 4,
    titleVi: 'Bí Cảnh Huyết Nguyệt',
    titleEn: 'Blood Moon Secret Realm',
    descriptionVi: 'Bí Cảnh Huyết Nguyệt mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Blood Moon Secret Realm opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch03_main_15', descriptionVi: 'Hoàn thành chương 3 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 3 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'truc_co', requiredRealmOrder: 2, requiredCultivationStage: 1, requiredBattlePower: 2600, requiredMainQuestKey: 'phase21_ch03_main_15', previousChapterKey: 'chapter_tong_mon_so_khoi', requiredStoryFlag: 'story_flag_sect_array_repaired', requiredDungeonClearKey: 'story_dgn_truc_co_co_thu_ky', requiredBossDefeatedKey: 'moc_dinh_co_yeu', requiredSectRank: 'noi_mon', requiredElementalAffinity: 'thuy', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 4: cần truc_co, tầng 1, lực chiến 2600, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 4 gate: requires truc_co, stage 1, battle power 2600, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'truc_co',
    requiredRealmOrder: 2,
    mainQuestChainKey: 'phase21_chapter_04_main',
    mainQuestKeys: ['phase21_ch04_main_01', 'phase21_ch04_main_02', 'phase21_ch04_main_03', 'phase21_ch04_main_04', 'phase21_ch04_main_05', 'phase21_ch04_main_06', 'phase21_ch04_main_07', 'phase21_ch04_main_08', 'phase21_ch04_main_09', 'phase21_ch04_main_10', 'phase21_ch04_main_11', 'phase21_ch04_main_12', 'phase21_ch04_main_13', 'phase21_ch04_main_14', 'phase21_ch04_main_15'],
    involvedNpcKeys: ['npc_to_nguyet_ly', 'npc_lang_van_sinh', 'npc_moc_thanh_y', 'npc_han_da'],
    relatedDungeonKeys: ['story_dgn_truc_co_huyet_nguyet'],
    relatedBossKeys: ['moc_dinh_co_yeu'],
    chapterReward: { linhThach: 820, exp: 2900, congHien: 130, items: [{ itemKey: 'huyet_chi_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_04_complete'], titleKeys: ['phase21_title_bi_canh_khai_mon'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE: Blood Moon secret realm, erased Hoa Thiên branches, and old inheritance memory.',
  },
  {
    chapterKey: 'chapter_ma_tu_xuat_the',
    order: 5,
    titleVi: 'Ma Tu Xuất Thế',
    titleEn: 'Demonic Cultivator Emerges',
    descriptionVi: 'Ma Tu Xuất Thế mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Demonic Cultivator Emerges opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch04_main_15', descriptionVi: 'Hoàn thành chương 4 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 4 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'truc_co', requiredRealmOrder: 2, requiredCultivationStage: 5, requiredBattlePower: 4200, requiredMainQuestKey: 'phase21_ch04_main_15', previousChapterKey: 'chapter_bi_canh_huyet_nguyet', requiredStoryFlag: 'story_flag_huyet_nguyet_truth_seen', requiredDungeonClearKey: 'story_dgn_truc_co_huyet_nguyet', requiredBossDefeatedKey: 'huyet_long_quan', requiredSectRank: 'noi_mon', requiredElementalAffinity: 'hoa', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 5: cần truc_co, tầng 5, lực chiến 4200, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 5 gate: requires truc_co, stage 5, battle power 4200, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'truc_co',
    requiredRealmOrder: 2,
    mainQuestChainKey: 'phase21_chapter_05_main',
    mainQuestKeys: ['phase21_ch05_main_01', 'phase21_ch05_main_02', 'phase21_ch05_main_03', 'phase21_ch05_main_04', 'phase21_ch05_main_05', 'phase21_ch05_main_06', 'phase21_ch05_main_07', 'phase21_ch05_main_08', 'phase21_ch05_main_09', 'phase21_ch05_main_10', 'phase21_ch05_main_11', 'phase21_ch05_main_12', 'phase21_ch05_main_13', 'phase21_ch05_main_14', 'phase21_ch05_main_15'],
    involvedNpcKeys: ['npc_huyet_la_sat', 'npc_moc_thanh_y', 'npc_han_da', 'npc_huyet_ha_su_gia'],
    relatedDungeonKeys: ['story_dgn_kim_dan_huyet_thach_dong'],
    relatedBossKeys: ['huyet_long_quan'],
    chapterReward: { linhThach: 980, exp: 3550, congHien: 155, items: [{ itemKey: 'thanh_lam_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_05_complete'], titleKeys: ['phase21_title_ma_dao_tham_van'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE: Huyết La Sát moral-choice line and righteous/demonic ambiguity.',
  },
  {
    chapterKey: 'chapter_ngu_hanh_thien_menh',
    order: 6,
    titleVi: 'Ngũ Hành Thiên Mệnh',
    titleEn: 'Five-Element Heavenly Mandate',
    descriptionVi: 'Ngũ Hành Thiên Mệnh mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Five-Element Heavenly Mandate opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch05_main_15', descriptionVi: 'Hoàn thành chương 5 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 5 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'kim_dan', requiredRealmOrder: 3, requiredCultivationStage: 1, requiredBattlePower: 7200, requiredMainQuestKey: 'phase21_ch05_main_15', previousChapterKey: 'chapter_ma_tu_xuat_the', requiredStoryFlag: 'story_flag_huyet_la_sat_choice_made', requiredDungeonClearKey: 'story_dgn_kim_dan_huyet_thach_dong', requiredBossDefeatedKey: 'chu_tuoc_huyet_de', requiredSectRank: 'chan_truyen', requiredElementalAffinity: 'any', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 6: cần kim_dan, tầng 1, lực chiến 7200, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 6 gate: requires kim_dan, stage 1, battle power 7200, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'kim_dan',
    requiredRealmOrder: 3,
    mainQuestChainKey: 'phase21_chapter_06_main',
    mainQuestKeys: ['phase21_ch06_main_01', 'phase21_ch06_main_02', 'phase21_ch06_main_03', 'phase21_ch06_main_04', 'phase21_ch06_main_05', 'phase21_ch06_main_06', 'phase21_ch06_main_07', 'phase21_ch06_main_08', 'phase21_ch06_main_09', 'phase21_ch06_main_10', 'phase21_ch06_main_11', 'phase21_ch06_main_12', 'phase21_ch06_main_13', 'phase21_ch06_main_14', 'phase21_ch06_main_15'],
    involvedNpcKeys: ['npc_lang_van_sinh', 'npc_moc_thanh_y', 'npc_han_da', 'npc_to_nguyet_ly', 'npc_huyet_la_sat'],
    relatedDungeonKeys: ['story_dgn_kim_dan_ngu_hanh_te_dan'],
    relatedBossKeys: ['kim_phach_long_dieu'],
    chapterReward: { linhThach: 1140, exp: 4200, congHien: 180, items: [{ itemKey: 'skill_book_kim_quang_tram', qty: 1 }], achievementKeys: ['phase21_story_chapter_06_complete'], titleKeys: ['phase21_title_ngu_hanh_thien_menh'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE + AI_EXPANDED_LORE: Ngũ Hành awakening, party pressure, and the first explicit Tịch Thiên signal.',
  },
  {
    chapterKey: 'chapter_tam_ma_dai_su_ty',
    order: 7,
    titleVi: 'Tâm Ma Của Đại Sư Tỷ',
    titleEn: 'Senior Sister’s Heart Demon',
    descriptionVi: 'Tâm Ma Của Đại Sư Tỷ mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Senior Sister’s Heart Demon opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch06_main_15', descriptionVi: 'Hoàn thành chương 6 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 6 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'nguyen_anh', requiredRealmOrder: 4, requiredCultivationStage: 1, requiredBattlePower: 11000, requiredMainQuestKey: 'phase21_ch06_main_15', previousChapterKey: 'chapter_ngu_hanh_thien_menh', requiredStoryFlag: 'story_flag_tich_linh_seed_resonates', requiredDungeonClearKey: 'story_dgn_kim_dan_ngu_hanh_te_dan', requiredBossDefeatedKey: 'kim_phach_long_dieu', requiredSectRank: 'chan_truyen', requiredElementalAffinity: 'moc', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 7: cần nguyen_anh, tầng 1, lực chiến 11000, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 7 gate: requires nguyen_anh, stage 1, battle power 11000, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'nguyen_anh',
    requiredRealmOrder: 4,
    mainQuestChainKey: 'phase21_chapter_07_main',
    mainQuestKeys: ['phase21_ch07_main_01', 'phase21_ch07_main_02', 'phase21_ch07_main_03', 'phase21_ch07_main_04', 'phase21_ch07_main_05', 'phase21_ch07_main_06', 'phase21_ch07_main_07', 'phase21_ch07_main_08', 'phase21_ch07_main_09', 'phase21_ch07_main_10', 'phase21_ch07_main_11', 'phase21_ch07_main_12', 'phase21_ch07_main_13', 'phase21_ch07_main_14', 'phase21_ch07_main_15'],
    involvedNpcKeys: ['npc_moc_thanh_y', 'npc_lang_van_sinh', 'npc_tich_linh_su_gia'],
    relatedDungeonKeys: ['story_dgn_nguyen_anh_tam_canh_moc_thanh_y'],
    relatedBossKeys: ['cuu_u_yeu_hau'],
    chapterReward: { linhThach: 1300, exp: 4850, congHien: 205, items: [{ itemKey: 'thanh_lam_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_07_complete'], titleKeys: ['phase21_title_thanh_tam_ho_dao'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE: Mộc Thanh Y is tied to Tịch Thiên Điện through Tịch Linh Chủng; AI_EXPANDED_LORE turns that rescue into a gated Nguyên Anh arc.',
  },
  {
    chapterKey: 'chapter_hoa_thien_son_tang_mot',
    order: 8,
    titleVi: 'Hoa Thiên Sơn Tầng Một',
    titleEn: 'Hoa Thiên Mountain First Layer',
    descriptionVi: 'Hoa Thiên Sơn Tầng Một mở bằng điều kiện sức mạnh/cốt truyện rõ ràng và gồm 15 nhiệm vụ chính tuyến.',
    descriptionEn: 'Hoa Thiên Mountain First Layer opens through explicit power and story gates and contains 15 main quests.',
    unlockCondition: { kind: 'multi_gate', questKey: 'phase21_ch07_main_15', descriptionVi: 'Hoàn thành chương 7 và đủ gate sức mạnh.', descriptionEn: 'Complete chapter 7 and meet power gates.' },
    unlockGate: {
      requiredRealmKey: 'hoa_than', requiredRealmOrder: 5, requiredCultivationStage: 1, requiredBattlePower: 16000, requiredMainQuestKey: 'phase21_ch07_main_15', previousChapterKey: 'chapter_tam_ma_dai_su_ty', requiredStoryFlag: 'story_flag_moc_thanh_y_seed_stabilized', requiredDungeonClearKey: 'story_dgn_nguyen_anh_tam_canh_moc_thanh_y', requiredBossDefeatedKey: 'cuu_u_yeu_hau', requiredSectRank: 'hoa_thien_ho_phap', requiredElementalAffinity: 'any', runtimeStatus: 'catalog_seeded_runtime_follow_up',
      descriptionVi: 'Gate chương 8: cần hoa_than, tầng 1, lực chiến 16000, điều kiện cốt truyện và bí cảnh/boss liên quan nếu có.',
      descriptionEn: 'Chapter 8 gate: requires hoa_than, stage 1, battle power 16000, story flags, and linked dungeon/boss gates when present.',
    },
    requiredRealmKey: 'hoa_than',
    requiredRealmOrder: 5,
    mainQuestChainKey: 'phase21_chapter_08_main',
    mainQuestKeys: ['phase21_ch08_main_01', 'phase21_ch08_main_02', 'phase21_ch08_main_03', 'phase21_ch08_main_04', 'phase21_ch08_main_05', 'phase21_ch08_main_06', 'phase21_ch08_main_07', 'phase21_ch08_main_08', 'phase21_ch08_main_09', 'phase21_ch08_main_10', 'phase21_ch08_main_11', 'phase21_ch08_main_12', 'phase21_ch08_main_13', 'phase21_ch08_main_14', 'phase21_ch08_main_15'],
    involvedNpcKeys: ['npc_lang_van_sinh', 'npc_hoa_thien_dao_to', 'npc_tich_linh_su_gia'],
    relatedDungeonKeys: ['story_dgn_hoa_than_hoa_thien_son_first_layer'],
    relatedBossKeys: ['cuu_la_thien_de'],
    chapterReward: { linhThach: 1460, exp: 5500, congHien: 230, items: [{ itemKey: 'cuu_huyen_dan', qty: 1 }], achievementKeys: ['phase21_story_chapter_08_complete'], titleKeys: ['phase21_title_hoa_thien_ho_phap'] },
    loreSummary: 'CANON_FROM_STORY_BIBLE + AI_EXPANDED_LORE: first Hoa Thiên Mountain seal layer, scripture hall, and the next Tịch Thiên envoy escalation.',
  }
];

export function storyChapterByKey(chapterKey: string): StoryChapterDef | undefined { return STORY_CHAPTERS.find((chapter) => chapter.chapterKey === chapterKey); }
export function storyChaptersByQuestChain(chainKey: string): readonly StoryChapterDef[] { return STORY_CHAPTERS.filter((chapter) => chapter.mainQuestChainKey === chainKey); }
export function storyChaptersUnlockedAtRealm(requiredRealmOrder: number): readonly StoryChapterDef[] { return STORY_CHAPTERS.filter((chapter) => chapter.requiredRealmOrder <= requiredRealmOrder); }
